export type ReviewDecision = 'passed' | 'blocked_high' | 'blocked_unavailable';
export type ReviewSeverity = 'HIGH' | 'MEDIUM' | 'LOW';
export type ReviewCategory = 'security' | 'breaking_change' | 'quality' | 'style';
export interface CodeReviewFinding { readonly severity: ReviewSeverity; readonly category: ReviewCategory; readonly file: string; readonly lineHint: string; readonly description: string; }
export interface AutoCodeReviewResult { readonly decision: ReviewDecision; readonly passed: boolean; readonly summary: string; readonly findings: readonly CodeReviewFinding[]; readonly highCount: number; readonly mediumCount: number; readonly lowCount: number; readonly modelUsed: string; readonly resolvedTransport: string; readonly routeId: string; readonly fallbackUsed: boolean; readonly attemptedRouteCount: number; readonly error: string; readonly reviewedAt: number; }
export interface AutoCodeReviewRequest { readonly jobId: string; readonly backendBase: string; readonly fetcher?: typeof fetch; }
export function reviewAllowsDraftPr(result: AutoCodeReviewResult): boolean { return result.decision === 'passed' && result.passed; }
export function reviewBlockerMessage(result: AutoCodeReviewResult): string { if (result.decision === 'blocked_high') return `Auto Code Review: ${result.highCount} HIGH finding(s) must be resolved. ${result.summary}`; if (result.decision === 'blocked_unavailable') return `Auto Code Review unavailable: ${result.error || result.summary}`; return ''; }
export function findingsByFile(findings: readonly CodeReviewFinding[]): Map<string, readonly CodeReviewFinding[]> { const map = new Map<string, CodeReviewFinding[]>(); for (const finding of findings) map.set(finding.file, [...(map.get(finding.file) ?? []), finding]); return map; }
export function severityIcon(severity: ReviewSeverity): string { return ({ HIGH: '🔴', MEDIUM: '🟡', LOW: '🟢' } as const)[severity]; }
export function categoryLabel(category: ReviewCategory): string { return ({ security: 'Security', breaking_change: 'Breaking Change', quality: 'Qualität', style: 'Style' } as const)[category]; }
function unavailable(jobId: string, error: string): AutoCodeReviewResult { return { decision: 'blocked_unavailable', passed: false, summary: 'Auto code review unavailable.', findings: [], highCount: 0, mediumCount: 0, lowCount: 0, modelUsed: '', resolvedTransport: '', routeId: '', fallbackUsed: false, attemptedRouteCount: 0, error: jobId ? error : 'jobId is required', reviewedAt: Date.now() }; }
export async function requestAutoCodeReview(request: AutoCodeReviewRequest): Promise<AutoCodeReviewResult> {
  const jobId = request.jobId.trim(); if (!jobId) return unavailable('', 'jobId is required'); let response: Response;
  try { response = await (request.fetcher ?? fetch)(`${request.backendBase.replace(/\/$/, '')}/api/user/agent/jobs/${encodeURIComponent(jobId)}/review`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: '{}' }); }
  catch (error) { return unavailable(jobId, error instanceof Error ? error.message : String(error)); }
  let body: Record<string, unknown> = {}; try { body = await response.json() as Record<string, unknown>; } catch { body = {}; }
  const decision = ['passed', 'blocked_high', 'blocked_unavailable'].includes(String(body.decision)) ? String(body.decision) as ReviewDecision : 'blocked_unavailable';
  const findings = Array.isArray(body.findings) ? body.findings.filter((item): item is Record<string, unknown> => typeof item === 'object' && item !== null).map((item): CodeReviewFinding => ({ severity: ['HIGH', 'MEDIUM', 'LOW'].includes(String(item.severity)) ? String(item.severity) as ReviewSeverity : 'LOW', category: ['security', 'breaking_change', 'quality', 'style'].includes(String(item.category)) ? String(item.category) as ReviewCategory : 'quality', file: String(item.file ?? 'general'), lineHint: String(item.lineHint ?? item.line_hint ?? ''), description: String(item.description ?? '') })) : [];
  const result: AutoCodeReviewResult = { decision, passed: body.passed === true, summary: String(body.summary ?? ''), findings, highCount: Number(body.highCount ?? 0), mediumCount: Number(body.mediumCount ?? 0), lowCount: Number(body.lowCount ?? 0), modelUsed: String(body.modelUsed ?? ''), resolvedTransport: String(body.resolvedTransport ?? ''), routeId: String(body.routeId ?? ''), fallbackUsed: body.fallbackUsed === true, attemptedRouteCount: Number(body.attemptedRouteCount ?? 0), error: String(body.error ?? ''), reviewedAt: Date.now() };
  if (!response.ok && decision === 'passed') return unavailable(jobId, `HTTP ${response.status}`); return result;
}
