import type { ContainerDecisionRule } from './containerDecisionGrammar';
import { KNOWN_CONTAINER_IDS, assertContainerDecisionRulesValid } from './containerDecisionGrammar';

function buildPatternRules(): ContainerDecisionRule[] {
  return [
    // Repo Snapshot patterns
    {
      id: 'repo-snapshot:ready',
      containerId: 'repo-snapshot',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['repo ready', 'snapshot loaded', 'repository loaded', 'repo files available', 'repo snapshot green'],
      minScore: 1,
      learnTag: 'repo-snapshot.ready',
      nextAction: 'Proceed to Builder with loaded repository.',
    },
    {
      id: 'repo-snapshot:missing',
      containerId: 'repo-snapshot',
      priority: 85,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['repo fehlt', 'repo missing', 'no repository loaded', 'repository snapshot is not ready', 'no repo loaded'],
      blockers: ['repo ready', 'snapshot loaded'],
      minScore: 1,
      learnTag: 'repo-snapshot.missing',
      nextAction: 'Request repository URL and load snapshot.',
    },
    {
      id: 'repo-snapshot:token-required',
      containerId: 'repo-snapshot',
      priority: 70,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['private token required', 'private repo needs token', 'token required for private repo', 'authentication required'],
      minScore: 1,
      learnTag: 'repo-snapshot.token-required',
      nextAction: 'Request GitHub private access token for private repository.',
    },
    {
      id: 'repo-snapshot:load-failed',
      containerId: 'repo-snapshot',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['load failed', 'repository load failed', 'failed to load repo', 'repo load error', 'snapshot error'],
      blockers: ['repo ready', 'snapshot loaded'],
      minScore: 1,
      learnTag: 'repo-snapshot.load-failed',
      nextAction: 'Check repository URL, token validity, and network connectivity. Retry load.',
    },
    {
      id: 'repo-snapshot:stale',
      containerId: 'repo-snapshot',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['snapshot stale', 'repo outdated', 'needs refresh', 'snapshot expired'],
      minScore: 1,
      learnTag: 'repo-snapshot.stale',
      nextAction: 'Refresh repository snapshot to get latest changes.',
    },
    {
      id: 'repo-snapshot:invalid-url',
      containerId: 'repo-snapshot',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['invalid repo url', 'invalid repository url', 'url parse error', 'invalid github url'],
      minScore: 1,
      learnTag: 'repo-snapshot.invalid-url',
      nextAction: 'Check repository URL format. Use format: https://github.com/owner/repository',
    },
    {
      id: 'repo-snapshot:private-access-needed',
      containerId: 'repo-snapshot',
      priority: 75,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['private repository', 'private repo', 'requires authentication', 'access denied', '403'],
      minScore: 1,
      learnTag: 'repo-snapshot.private-access',
      nextAction: 'Request private access token for private repository.',
    },
    {
      id: 'repo-snapshot:loading',
      containerId: 'repo-snapshot',
      priority: 60,
      lamp: 'green',
      action: 'continue',
      signals: ['loading repository', 'loading repo', 'fetching files', 'scanning repository'],
      minScore: 1,
      learnTag: 'repo-snapshot.loading',
      nextAction: 'Wait for repository to finish loading.',
    },
    {
      id: 'repo-snapshot:network-error',
      containerId: 'repo-snapshot',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['network error', 'connection failed', 'timeout', 'fetch error', 'no internet'],
      blockers: ['repo ready', 'snapshot loaded'],
      minScore: 1,
      learnTag: 'repo-snapshot.network-error',
      nextAction: 'Check network connectivity and retry repository loading.',
    },
    {
      id: 'repo-snapshot:branch-missing',
      containerId: 'repo-snapshot',
      priority: 65,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['no branch', 'branch not found', 'default branch', 'main branch'],
      minScore: 1,
      learnTag: 'repo-snapshot.branch-missing',
      nextAction: 'Select or confirm branch to use.',
    },
    {
      id: 'repo-snapshot:empty-repo',
      containerId: 'repo-snapshot',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['empty repository', 'no files', 'empty repo', 'repository empty'],
      minScore: 1,
      learnTag: 'repo-snapshot.empty',
      nextAction: 'Verify repository has content or select different repository.',
    },

    // Builder patterns
    {
      id: 'builder:ready',
      containerId: 'builder',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['mission ready', 'builder ready', 'goal set', 'package build ready', 'mission accepted'],
      minScore: 1,
      learnTag: 'builder.ready',
      nextAction: 'Execute package build with current mission.',
    },
    {
      id: 'builder:goal-missing',
      containerId: 'builder',
      priority: 85,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['goal missing', 'no mission set', 'mission empty', 'please enter your goal', 'was willst du'],
      blockers: ['mission ready', 'goal set'],
      minScore: 1,
      learnTag: 'builder.goal-missing',
      nextAction: 'Request user goal or mission description.',
    },
    {
      id: 'builder:placeholder-mission',
      containerId: 'builder',
      priority: 80,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['placeholder mission', 'example mission', 'demo goal', 'sample task'],
      blockers: ['mission ready', 'concrete mission'],
      minScore: 1,
      learnTag: 'builder.placeholder',
      nextAction: 'Replace placeholder with concrete user goal.',
    },
    {
      id: 'builder:package-build-active',
      containerId: 'builder',
      priority: 90,
      lamp: 'green',
      action: 'continue',
      signals: ['package build active', 'building package', 'package-build running', 'generating files'],
      minScore: 1,
      learnTag: 'builder.package-build',
      nextAction: 'Monitor package build progress.',
    },
    {
      id: 'builder:full-auto-active',
      containerId: 'builder',
      priority: 85,
      lamp: 'green',
      action: 'continue',
      signals: ['full auto active', 'automation running', 'auto mode enabled'],
      minScore: 1,
      learnTag: 'builder.full-auto',
      nextAction: 'Continue automated workflow execution.',
    },
    {
      id: 'builder:rewrite-requested',
      containerId: 'builder',
      priority: 75,
      lamp: 'yellow',
      action: 'review',
      signals: ['rewrite requested', 'revision needed', 'changes required', 'rewrite mission'],
      minScore: 1,
      learnTag: 'builder.rewrite',
      nextAction: 'Review and regenerate package with updated mission.',
    },
    {
      id: 'builder:plan-only-blocked',
      containerId: 'builder',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['plan only', 'planning mode', 'no execution', 'skip build'],
      blockers: ['package build active', 'full auto active'],
      minScore: 1,
      learnTag: 'builder.plan-only',
      nextAction: 'Consider enabling execution mode for actual file generation.',
    },
    {
      id: 'builder:intent-detected',
      containerId: 'builder',
      priority: 85,
      lamp: 'green',
      action: 'continue',
      signals: ['intent detected', 'goal captured', 'mission parsed', 'task understood'],
      minScore: 1,
      learnTag: 'builder.intent-detected',
      nextAction: 'Process detected intent and generate mission.',
    },
    {
      id: 'builder:build-error',
      containerId: 'builder',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['build error', 'build failed', 'compilation error', 'syntax error', 'build crashed'],
      minScore: 1,
      learnTag: 'builder.build-error',
      nextAction: 'Fix build errors and retry package generation.',
    },
    {
      id: 'builder:timeout',
      containerId: 'builder',
      priority: 75,
      lamp: 'yellow',
      action: 'review',
      signals: ['build timeout', 'timeout exceeded', 'taking too long', 'build stalled'],
      minScore: 1,
      learnTag: 'builder.timeout',
      nextAction: 'Check build complexity and optimize or cancel.',
    },
    {
      id: 'builder:quality-low',
      containerId: 'builder',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['low quality', 'quality concerns', 'needs improvement', 'suboptimal output'],
      minScore: 1,
      learnTag: 'builder.quality-low',
      nextAction: 'Review output quality and consider regeneration.',
    },
    {
      id: 'builder:awaiting-input',
      containerId: 'builder',
      priority: 80,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['awaiting input', 'waiting for response', 'need clarification', 'more info needed'],
      minScore: 1,
      learnTag: 'builder.awaiting-input',
      nextAction: 'Request additional information from user.',
    },
    {
      id: 'builder:idle',
      containerId: 'builder',
      priority: 30,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['builder idle', 'no active task', 'ready for input', 'waiting for mission'],
      minScore: 1,
      learnTag: 'builder.idle',
      nextAction: 'Request user mission or goal.',
    },

    // Generated Files patterns
    {
      id: 'generated-files:accepted',
      containerId: 'generated-files',
      priority: 90,
      lamp: 'green',
      action: 'continue',
      signals: ['self review: accepted', 'files accepted', 'generated-output-accepted', 'files passed review'],
      minScore: 1,
      learnTag: 'generated-files.accepted',
      nextAction: 'Proceed to diff preview or draft PR.',
    },
    {
      id: 'generated-files:review-accepted',
      containerId: 'generated-files',
      priority: 85,
      lamp: 'green',
      action: 'continue',
      signals: ['review accepted', 'generated package passed self review', 'pre-publish review passed'],
      minScore: 1,
      learnTag: 'generated-files.review-accepted',
      nextAction: 'Ready for diff preview and draft PR creation.',
    },
    {
      id: 'generated-files:rejected',
      containerId: 'generated-files',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['self review: rejected', 'files rejected', 'review failed', 'generated-output-rejected'],
      minScore: 1,
      learnTag: 'generated-files.rejected',
      nextAction: 'Review rejection reasons and regenerate files.',
    },
    {
      id: 'generated-files:rewrite-needed',
      containerId: 'generated-files',
      priority: 80,
      lamp: 'yellow',
      action: 'review',
      signals: ['rewrite needed', 'files need revision', 'partial review', 'some files rejected'],
      minScore: 1,
      learnTag: 'generated-files.rewrite-needed',
      nextAction: 'Review partial rejection and regenerate affected files.',
    },
    {
      id: 'generated-files:plan-only',
      containerId: 'generated-files',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['plan only mode', 'no files generated', 'only planning', 'skip file generation'],
      blockers: ['files accepted', 'self review: accepted'],
      minScore: 1,
      learnTag: 'generated-files.plan-only',
      nextAction: 'Consider enabling file generation mode.',
    },
    {
      id: 'generated-files:audit-only',
      containerId: 'generated-files',
      priority: 65,
      lamp: 'yellow',
      action: 'review',
      signals: ['audit only', 'review only', 'no changes planned', 'skip generation'],
      blockers: ['files accepted', 'self review: accepted'],
      minScore: 1,
      learnTag: 'generated-files.audit-only',
      nextAction: 'Consider enabling actual file generation for production.',
    },
    {
      id: 'generated-files:actionable-present',
      containerId: 'generated-files',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['actionable files present', 'files ready', 'output ready', 'generated file'],
      minScore: 1,
      learnTag: 'generated-files.actionable',
      nextAction: 'Review generated files and proceed to diff.',
    },
    {
      id: 'generated-files:self-review-failed',
      containerId: 'generated-files',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['self review failed', 'review error', 'validation failed', 'quality check failed'],
      minScore: 1,
      learnTag: 'generated-files.self-review-failed',
      nextAction: 'Address validation errors and regenerate files.',
    },

    // Diff Preview patterns
    {
      id: 'diff-preview:ready',
      containerId: 'diff-preview',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['diff ready', 'diff preview ready', 'diff loaded', 'preview available'],
      minScore: 1,
      learnTag: 'diff-preview.ready',
      nextAction: 'Review diff and proceed to draft PR.',
    },
    {
      id: 'diff-preview:missing',
      containerId: 'diff-preview',
      priority: 85,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['diff missing', 'no diff available', 'preview not ready', 'diff not loaded'],
      blockers: ['diff ready', 'diff loaded'],
      minScore: 1,
      learnTag: 'diff-preview.missing',
      nextAction: 'Generate diff preview from accepted files.',
    },
    {
      id: 'diff-preview:source-missing',
      containerId: 'diff-preview',
      priority: 80,
      lamp: 'yellow',
      action: 'review',
      signals: ['source missing', 'cannot generate diff', 'source file not found', 'missing source'],
      minScore: 1,
      learnTag: 'diff-preview.source-missing',
      nextAction: 'Ensure source files are loaded before generating diff.',
    },
    {
      id: 'diff-preview:unchanged',
      containerId: 'diff-preview',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['unchanged output', 'no changes detected', 'diff empty', 'no modifications'],
      minScore: 1,
      learnTag: 'diff-preview.unchanged',
      nextAction: 'Verify files were actually modified.',
    },
    {
      id: 'diff-preview:new-file',
      containerId: 'diff-preview',
      priority: 70,
      lamp: 'green',
      action: 'continue',
      signals: ['new file', 'file added', 'created file', 'addition'],
      minScore: 1,
      learnTag: 'diff-preview.new-file',
      nextAction: 'Review new file additions in diff.',
    },
    {
      id: 'diff-preview:risky-replacement',
      containerId: 'diff-preview',
      priority: 85,
      lamp: 'yellow',
      action: 'review',
      signals: ['risky replacement', 'dangerous change', 'overwrite detected', 'caution recommended'],
      minScore: 1,
      learnTag: 'diff-preview.risky',
      nextAction: 'Carefully review risky file replacements before committing.',
    },
    {
      id: 'diff-preview:deleted-file',
      containerId: 'diff-preview',
      priority: 65,
      lamp: 'yellow',
      action: 'review',
      signals: ['file deleted', 'deletion', 'file removed', 'deleted'],
      minScore: 1,
      learnTag: 'diff-preview.deleted',
      nextAction: 'Review deleted files in diff.',
    },
    {
      id: 'diff-preview:large-change',
      containerId: 'diff-preview',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['large diff', 'many changes', 'extensive modifications', 'major changes'],
      minScore: 1,
      learnTag: 'diff-preview.large-change',
      nextAction: 'Review large diff carefully before committing.',
    },
    {
      id: 'diff-preview:loading',
      containerId: 'diff-preview',
      priority: 50,
      lamp: 'green',
      action: 'continue',
      signals: ['loading diff', 'generating diff', 'computing diff', 'diff loading'],
      minScore: 1,
      learnTag: 'diff-preview.loading',
      nextAction: 'Wait for diff to finish loading.',
    },

    // Workflow patterns
    {
      id: 'workflow:pending',
      containerId: 'workflow',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['workflow pending', 'checks pending', 'waiting for workflow', 'workflow running'],
      minScore: 1,
      learnTag: 'workflow.pending',
      nextAction: 'Wait for workflow checks to complete.',
    },
    {
      id: 'workflow:green',
      containerId: 'workflow',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['workflow green', 'checks passed', 'all checks passed', 'workflow success'],
      minScore: 1,
      learnTag: 'workflow.green',
      nextAction: 'Workflow checks passed. Safe to merge.',
    },
    {
      id: 'workflow:red',
      containerId: 'workflow',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['workflow red', 'checks failed', 'workflow failed', 'build failed', 'test failed'],
      minScore: 1,
      learnTag: 'workflow.red',
      nextAction: 'Analyze failed checks and prepare repair plan.',
    },
    {
      id: 'workflow:checks-missing',
      containerId: 'workflow',
      priority: 65,
      lamp: 'yellow',
      action: 'review',
      signals: ['checks missing', 'no checks configured', 'workflow not set up', 'missing checks'],
      minScore: 1,
      learnTag: 'workflow.checks-missing',
      nextAction: 'Consider setting up CI checks for quality assurance.',
    },
    {
      id: 'workflow:stale',
      containerId: 'workflow',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['stale commit', 'workflow stale', 'outdated result', 'needs refresh'],
      minScore: 1,
      learnTag: 'workflow.stale',
      nextAction: 'Refresh workflow status for current commit.',
    },
    {
      id: 'workflow:repair-available',
      containerId: 'workflow',
      priority: 85,
      lamp: 'yellow',
      action: 'repair',
      signals: ['repair available', 'repair plan ready', 'can repair', 'fix available'],
      minScore: 1,
      learnTag: 'workflow.repair-available',
      nextAction: 'Execute repair plan to fix workflow failures.',
    },
    {
      id: 'workflow:cancelled',
      containerId: 'workflow',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['workflow cancelled', 'checks cancelled', 'cancelled', 'aborted'],
      minScore: 1,
      learnTag: 'workflow.cancelled',
      nextAction: 'Review cancelled workflow and restart if needed.',
    },
    {
      id: 'workflow:retry-available',
      containerId: 'workflow',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['retry available', 'can retry', 'retry possible', 'rerun'],
      minScore: 1,
      learnTag: 'workflow.retry-available',
      nextAction: 'Retry failed workflow checks.',
    },

    // Remote Memory patterns
    {
      id: 'remote-memory:gateway-ready',
      containerId: 'remote-memory',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['gateway ready', 'memory connected', 'remote memory available', 'sync ready'],
      minScore: 1,
      learnTag: 'remote-memory.gateway-ready',
      nextAction: 'Remote memory gateway is connected and ready.',
    },
    {
      id: 'remote-memory:unreachable',
      containerId: 'remote-memory',
      priority: 85,
      lamp: 'red',
      action: 'repair',
      signals: ['gateway unreachable', 'memory connection failed', 'remote error', 'sync failed'],
      minScore: 1,
      learnTag: 'remote-memory.unreachable',
      nextAction: 'Check gateway URL, network connectivity, and authentication.',
    },
    {
      id: 'remote-memory:pull-available',
      containerId: 'remote-memory',
      priority: 70,
      lamp: 'green',
      action: 'continue',
      signals: ['pull update available', 'update ready', 'new patterns available', 'sync available'],
      minScore: 1,
      learnTag: 'remote-memory.pull-available',
      nextAction: 'Pull updates from remote memory to local cache.',
    },
    {
      id: 'remote-memory:sync-allowed',
      containerId: 'remote-memory',
      priority: 65,
      lamp: 'green',
      action: 'continue',
      signals: ['sync allowed', 'can sync', 'sync permitted', 'upload ready'],
      minScore: 1,
      learnTag: 'remote-memory.sync-allowed',
      nextAction: 'Sync local patterns to remote memory.',
    },
    {
      id: 'remote-memory:delete-confirmation',
      containerId: 'remote-memory',
      priority: 80,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['delete requires confirmation', 'confirm delete', 'deletion warning', 'delete check'],
      minScore: 1,
      learnTag: 'remote-memory.delete-confirm',
      nextAction: 'Require explicit user confirmation before deleting patterns.',
    },
    {
      id: 'remote-memory:preserve-shared',
      containerId: 'remote-memory',
      priority: 75,
      lamp: 'yellow',
      action: 'review',
      signals: ['preserve shared patterns', 'shared pattern detected', 'dont delete shared', 'shared warning'],
      minScore: 1,
      learnTag: 'remote-memory.preserve-shared',
      nextAction: 'Do not delete patterns that are shared with other workspaces.',
    },
    {
      id: 'remote-memory:contributor-only-erase',
      containerId: 'remote-memory',
      priority: 80,
      lamp: 'yellow',
      action: 'review',
      signals: ['contributor only erase', 'author erase only', 'delete by contributor', 'owner delete'],
      minScore: 1,
      learnTag: 'remote-memory.contributor-erase',
      nextAction: 'Only allow pattern deletion by original contributor.',
    },
    {
      id: 'remote-memory:syncing',
      containerId: 'remote-memory',
      priority: 60,
      lamp: 'green',
      action: 'continue',
      signals: ['syncing', 'synchronizing', 'sync in progress', 'pushing to remote'],
      minScore: 1,
      learnTag: 'remote-memory.syncing',
      nextAction: 'Wait for sync to complete.',
    },
    {
      id: 'remote-memory:conflict-detected',
      containerId: 'remote-memory',
      priority: 85,
      lamp: 'yellow',
      action: 'review',
      signals: ['conflict detected', 'merge conflict', 'sync conflict', 'conflicting changes'],
      minScore: 1,
      learnTag: 'remote-memory.conflict',
      nextAction: 'Resolve sync conflicts before continuing.',
    },
    {
      id: 'remote-memory:auth-required',
      containerId: 'remote-memory',
      priority: 80,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['authentication required', 'auth needed', 'login required', 'credentials expired'],
      minScore: 1,
      learnTag: 'remote-memory.auth-required',
      nextAction: 'Re-authenticate with remote memory service.',
    },
    {
      id: 'remote-memory:quota-exceeded',
      containerId: 'remote-memory',
      priority: 75,
      lamp: 'yellow',
      action: 'review',
      signals: ['quota exceeded', 'storage limit', 'memory full', 'quota reached'],
      minScore: 1,
      learnTag: 'remote-memory.quota-exceeded',
      nextAction: 'Consider cleaning up old patterns or upgrading storage.',
    },

    // Pattern Memory patterns
    {
      id: 'pattern-memory:learned',
      containerId: 'pattern-memory',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['pattern learned', 'new pattern saved', 'pattern stored', 'learning complete'],
      minScore: 1,
      learnTag: 'pattern-memory.learned',
      nextAction: 'Pattern successfully learned and stored.',
    },
    {
      id: 'pattern-memory:stale',
      containerId: 'pattern-memory',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['pattern stale', 'outdated pattern', 'pattern expired', 'stale learning'],
      minScore: 1,
      learnTag: 'pattern-memory.stale',
      nextAction: 'Review and refresh stale patterns.',
    },
    {
      id: 'pattern-memory:rejected',
      containerId: 'pattern-memory',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['pattern rejected', 'learning rejected', 'pattern failed', 'invalid pattern'],
      minScore: 1,
      learnTag: 'pattern-memory.rejected',
      nextAction: 'Review rejection reason and improve pattern quality.',
    },
    {
      id: 'pattern-memory:successful',
      containerId: 'pattern-memory',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['pattern successful', 'pattern applied', 'pattern worked', 'solution effective'],
      minScore: 1,
      learnTag: 'pattern-memory.successful',
      nextAction: 'Pattern successfully applied and validated.',
    },
    {
      id: 'pattern-memory:solution-selected',
      containerId: 'pattern-memory',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['solution pattern selected', 'pattern selected', 'best match found', 'solution chosen'],
      minScore: 1,
      learnTag: 'pattern-memory.solution-selected',
      nextAction: 'Apply selected solution pattern to current task.',
    },
    {
      id: 'pattern-memory:rewrite-available',
      containerId: 'pattern-memory',
      priority: 65,
      lamp: 'green',
      action: 'continue',
      signals: ['rewrite memory available', 'revision stored', 'improvement saved', 'update recorded'],
      minScore: 1,
      learnTag: 'pattern-memory.rewrite-available',
      nextAction: 'Use rewrite memory to improve future generations.',
    },
    {
      id: 'pattern-memory:imported',
      containerId: 'pattern-memory',
      priority: 70,
      lamp: 'green',
      action: 'continue',
      signals: ['pattern imported', 'imported from remote', 'pattern synced', 'pattern pulled'],
      minScore: 1,
      learnTag: 'pattern-memory.imported',
      nextAction: 'Pattern successfully imported from remote.',
    },
    {
      id: 'pattern-memory:exported',
      containerId: 'pattern-memory',
      priority: 70,
      lamp: 'green',
      action: 'continue',
      signals: ['pattern exported', 'published to remote', 'pattern pushed', 'pattern shared'],
      minScore: 1,
      learnTag: 'pattern-memory.exported',
      nextAction: 'Pattern successfully exported to remote.',
    },
    {
      id: 'pattern-memory:invalid',
      containerId: 'pattern-memory',
      priority: 80,
      lamp: 'red',
      action: 'repair',
      signals: ['invalid pattern', 'pattern corrupted', 'parse error', 'malformed pattern'],
      minScore: 1,
      learnTag: 'pattern-memory.invalid',
      nextAction: 'Fix or delete invalid pattern.',
    },
    {
      id: 'pattern-memory:low-confidence',
      containerId: 'pattern-memory',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['low confidence', 'uncertain pattern', 'weak match', 'needs validation'],
      minScore: 1,
      learnTag: 'pattern-memory.low-confidence',
      nextAction: 'Validate low-confidence patterns before use.',
    },

    // Telemetry patterns
    {
      id: 'telemetry:ok',
      containerId: 'telemetry',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['telemetry ok', 'events logged', 'tracking active', 'telemetry healthy'],
      minScore: 1,
      learnTag: 'telemetry.ok',
      nextAction: 'Telemetry tracking is healthy.',
    },
    {
      id: 'telemetry:warning',
      containerId: 'telemetry',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['telemetry warning', 'event warning', 'tracking issue', 'log warning'],
      minScore: 1,
      learnTag: 'telemetry.warning',
      nextAction: 'Review telemetry warnings and resolve issues.',
    },
    {
      id: 'telemetry:duplicate-event',
      containerId: 'telemetry',
      priority: 65,
      lamp: 'yellow',
      action: 'review',
      signals: ['duplicate event', 'event duplicated', 'repeated event', 'duplicate detected'],
      minScore: 1,
      learnTag: 'telemetry.duplicate',
      nextAction: 'Deduplicate telemetry events.',
    },
    {
      id: 'telemetry:missing-stage',
      containerId: 'telemetry',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['missing stage', 'stage not logged', 'incomplete stage', 'stage gap'],
      minScore: 1,
      learnTag: 'telemetry.missing-stage',
      nextAction: 'Add missing stage logging for complete telemetry.',
    },
    {
      id: 'telemetry:secret-risk',
      containerId: 'telemetry',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['secret risk', 'token exposed', 'credential logged', 'sensitive data detected'],
      minScore: 1,
      learnTag: 'telemetry.secret-risk',
      nextAction: 'Remove exposed secrets from telemetry and logs immediately.',
    },
    {
      id: 'telemetry:noisy-events',
      containerId: 'telemetry',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['noisy events', 'too many events', 'event flood', 'excessive logging'],
      minScore: 1,
      learnTag: 'telemetry.noisy',
      nextAction: 'Reduce event frequency and consolidate noisy events.',
    },
    {
      id: 'telemetry:mismatch',
      containerId: 'telemetry',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['latest by stage mismatch', 'stage mismatch', 'inconsistent state', 'telemetry mismatch'],
      minScore: 1,
      learnTag: 'telemetry.mismatch',
      nextAction: 'Fix telemetry consistency issues between stages.',
    },
    {
      id: 'telemetry:disabled',
      containerId: 'telemetry',
      priority: 50,
      lamp: 'yellow',
      action: 'review',
      signals: ['telemetry disabled', 'tracking off', 'events disabled', 'logging off'],
      minScore: 1,
      learnTag: 'telemetry.disabled',
      nextAction: 'Consider enabling telemetry for better insights.',
    },
    {
      id: 'telemetry:paused',
      containerId: 'telemetry',
      priority: 40,
      lamp: 'yellow',
      action: 'review',
      signals: ['telemetry paused', 'tracking paused', 'events paused', 'paused'],
      minScore: 1,
      learnTag: 'telemetry.paused',
      nextAction: 'Resume telemetry if needed.',
    },
    {
      id: 'telemetry:event-truncated',
      containerId: 'telemetry',
      priority: 55,
      lamp: 'yellow',
      action: 'review',
      signals: ['event truncated', 'log truncated', 'event cut off', 'incomplete event'],
      minScore: 1,
      learnTag: 'telemetry.truncated',
      nextAction: 'Check event size limits and adjust if needed.',
    },

    // Health patterns
    {
      id: 'health:green',
      containerId: 'health',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['health green', 'system healthy', 'all checks pass', 'status ok'],
      minScore: 1,
      learnTag: 'health.green',
      nextAction: 'System health is good. Continue operations.',
    },
    {
      id: 'health:warning',
      containerId: 'health',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['health warning', 'system warning', 'minor issues', 'health degraded'],
      minScore: 1,
      learnTag: 'health.warning',
      nextAction: 'Review health warnings and address minor issues.',
    },
    {
      id: 'health:red',
      containerId: 'health',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['health red', 'system critical', 'critical issues', 'health failure'],
      minScore: 1,
      learnTag: 'health.red',
      nextAction: 'Address critical health issues immediately.',
    },
    {
      id: 'health:degraded',
      containerId: 'health',
      priority: 75,
      lamp: 'yellow',
      action: 'review',
      signals: ['degraded', 'partial failure', 'some services down', 'degraded mode'],
      minScore: 1,
      learnTag: 'health.degraded',
      nextAction: 'Investigate degraded services and restore functionality.',
    },
    {
      id: 'health:mixed-report',
      containerId: 'health',
      priority: 65,
      lamp: 'yellow',
      action: 'review',
      signals: ['mixed report', 'inconsistent health', 'conflicting signals', 'mixed status'],
      minScore: 1,
      learnTag: 'health.mixed',
      nextAction: 'Resolve conflicting health signals for clear status.',
    },
    {
      id: 'health:release-blocked',
      containerId: 'health',
      priority: 85,
      lamp: 'red',
      action: 'repair',
      signals: ['release blocked', 'cannot release', 'publish blocked', 'release held'],
      minScore: 1,
      learnTag: 'health.release-blocked',
      nextAction: 'Resolve blocking issues before releasing.',
    },
    {
      id: 'health:checking',
      containerId: 'health',
      priority: 50,
      lamp: 'green',
      action: 'continue',
      signals: ['health checking', 'running diagnostics', 'scanning system', 'checking health'],
      minScore: 1,
      learnTag: 'health.checking',
      nextAction: 'Wait for health check to complete.',
    },
    {
      id: 'health:no-repo',
      containerId: 'health',
      priority: 60,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['no repository', 'health needs repo', 'repository required', 'no repo loaded'],
      minScore: 1,
      learnTag: 'health.no-repo',
      nextAction: 'Load repository to perform health check.',
    },

    // Runtime Coverage patterns
    {
      id: 'runtime-coverage:healthy',
      containerId: 'runtime-coverage',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['coverage healthy', 'runtime validation coverage', 'all guards active', 'validation complete'],
      minScore: 1,
      learnTag: 'runtime-coverage.healthy',
      nextAction: 'Runtime coverage is healthy. Continue operations.',
    },
    {
      id: 'runtime-coverage:gap',
      containerId: 'runtime-coverage',
      priority: 75,
      lamp: 'yellow',
      action: 'review',
      signals: ['coverage gap', 'missing coverage', 'validation gap', 'unguarded area'],
      minScore: 1,
      learnTag: 'runtime-coverage.gap',
      nextAction: 'Add runtime validation for uncovered areas.',
    },
    {
      id: 'runtime-coverage:missing-guard',
      containerId: 'runtime-coverage',
      priority: 80,
      lamp: 'yellow',
      action: 'review',
      signals: ['missing guard', 'no guard for', 'unguarded', 'guard missing'],
      minScore: 1,
      learnTag: 'runtime-coverage.missing-guard',
      nextAction: 'Implement missing runtime guard for critical path.',
    },
    {
      id: 'runtime-coverage:missing-test',
      containerId: 'runtime-coverage',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['missing test', 'test gap', 'untested', 'test coverage low'],
      minScore: 1,
      learnTag: 'runtime-coverage.missing-test',
      nextAction: 'Add test coverage for missing test cases.',
    },
    {
      id: 'runtime-coverage:weak',
      containerId: 'runtime-coverage',
      priority: 65,
      lamp: 'yellow',
      action: 'review',
      signals: ['weak coverage', 'low coverage', 'coverage below threshold', 'weak validation'],
      minScore: 1,
      learnTag: 'runtime-coverage.weak',
      nextAction: 'Strengthen runtime validation coverage.',
    },
    {
      id: 'runtime-coverage:release-blocked',
      containerId: 'runtime-coverage',
      priority: 85,
      lamp: 'red',
      action: 'repair',
      signals: ['coverage release blocked', 'insufficient coverage', 'validation required', 'coverage gate failed'],
      minScore: 1,
      learnTag: 'runtime-coverage.release-blocked',
      nextAction: 'Improve coverage to pass release gate.',
    },
    {
      id: 'runtime-coverage:increasing',
      containerId: 'runtime-coverage',
      priority: 60,
      lamp: 'green',
      action: 'continue',
      signals: ['coverage improving', 'guards added', 'validation increasing', 'more coverage'],
      minScore: 1,
      learnTag: 'runtime-coverage.increasing',
      nextAction: 'Coverage is improving. Continue adding guards.',
    },
    {
      id: 'runtime-coverage:stale',
      containerId: 'runtime-coverage',
      priority: 55,
      lamp: 'yellow',
      action: 'review',
      signals: ['coverage stale', 'outdated validation', 'old coverage', 'stale guards'],
      minScore: 1,
      learnTag: 'runtime-coverage.stale',
      nextAction: 'Review and update stale coverage data.',
    },

    // Findings patterns
    {
      id: 'findings:low',
      containerId: 'findings',
      priority: 60,
      lamp: 'green',
      action: 'continue',
      signals: ['finding low', 'low severity', 'minor finding', 'info level'],
      minScore: 1,
      learnTag: 'findings.low',
      nextAction: 'Log low severity findings for future reference.',
    },
    {
      id: 'findings:medium',
      containerId: 'findings',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['finding medium', 'medium severity', 'moderate finding', 'attention needed'],
      minScore: 1,
      learnTag: 'findings.medium',
      nextAction: 'Review medium severity findings and address if needed.',
    },
    {
      id: 'findings:high',
      containerId: 'findings',
      priority: 80,
      lamp: 'yellow',
      action: 'review',
      signals: ['finding high', 'high severity', 'serious finding', 'important issue'],
      minScore: 1,
      learnTag: 'findings.high',
      nextAction: 'Address high severity findings before proceeding.',
    },
    {
      id: 'findings:critical',
      containerId: 'findings',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['finding critical', 'critical finding', 'blocking issue', 'must fix'],
      minScore: 1,
      learnTag: 'findings.critical',
      nextAction: 'Fix critical findings immediately.',
    },
    {
      id: 'findings:duplicate',
      containerId: 'findings',
      priority: 55,
      lamp: 'green',
      action: 'continue',
      signals: ['duplicate finding', 'finding duplicated', 'already reported', 'duplicate detected'],
      minScore: 1,
      learnTag: 'findings.duplicate',
      nextAction: 'Mark duplicate findings as resolved.',
    },
    {
      id: 'findings:stale',
      containerId: 'findings',
      priority: 50,
      lamp: 'green',
      action: 'continue',
      signals: ['stale finding', 'outdated finding', 'old finding', 'finding expired'],
      minScore: 1,
      learnTag: 'findings.stale',
      nextAction: 'Archive or refresh stale findings.',
    },
    {
      id: 'findings:resolved',
      containerId: 'findings',
      priority: 60,
      lamp: 'green',
      action: 'continue',
      signals: ['finding resolved', 'issue fixed', 'finding closed', 'resolved'],
      minScore: 1,
      learnTag: 'findings.resolved',
      nextAction: 'Mark finding as resolved and update status.',
    },
    {
      id: 'findings:repair-priority',
      containerId: 'findings',
      priority: 75,
      lamp: 'yellow',
      action: 'repair',
      signals: ['repair priority', 'fix priority', 'repair needed', 'priority fix'],
      minScore: 1,
      learnTag: 'findings.repair-priority',
      nextAction: 'Create repair plan for high-priority findings.',
    },
    {
      id: 'findings:new',
      containerId: 'findings',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['new finding', 'new issue', 'fresh finding', 'just detected'],
      minScore: 1,
      learnTag: 'findings.new',
      nextAction: 'Review new finding and determine action.',
    },
    {
      id: 'findings:escalated',
      containerId: 'findings',
      priority: 80,
      lamp: 'red',
      action: 'repair',
      signals: ['finding escalated', 'issue escalated', 'severity increased', 'critical escalation'],
      minScore: 1,
      learnTag: 'findings.escalated',
      nextAction: 'Address escalated finding immediately.',
    },
    {
      id: 'findings:ignored',
      containerId: 'findings',
      priority: 40,
      lamp: 'green',
      action: 'continue',
      signals: ['finding ignored', 'issue ignored', 'accepted risk', 'will not fix'],
      minScore: 1,
      learnTag: 'findings.ignored',
      nextAction: 'Acknowledged finding as acceptable risk.',
    },
    {
      id: 'findings:false-positive',
      containerId: 'findings',
      priority: 50,
      lamp: 'green',
      action: 'continue',
      signals: ['false positive', 'not an issue', 'incorrect finding', 'rule error'],
      minScore: 1,
      learnTag: 'findings.false-positive',
      nextAction: 'Mark finding as false positive.',
    },

    // Sequential Runtime patterns
    {
      id: 'sequential-runtime:active-step',
      containerId: 'sequential-runtime',
      priority: 85,
      lamp: 'green',
      action: 'continue',
      signals: ['active step running', 'step in progress', 'currently executing', 'step running'],
      minScore: 1,
      learnTag: 'sequential-runtime.active-step',
      nextAction: 'Monitor active runtime step execution.',
    },
    {
      id: 'sequential-runtime:no-active-step',
      containerId: 'sequential-runtime',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['no active step', 'no step running', 'idle state', 'ready for next'],
      minScore: 1,
      learnTag: 'sequential-runtime.no-active-step',
      nextAction: 'Start next step in sequential runtime.',
    },
    {
      id: 'sequential-runtime:blocked-transition',
      containerId: 'sequential-runtime',
      priority: 80,
      lamp: 'red',
      action: 'repair',
      signals: ['blocked transition', 'transition blocked', 'cannot proceed', 'step blocked'],
      minScore: 1,
      learnTag: 'sequential-runtime.blocked',
      nextAction: 'Resolve blocking condition and retry transition.',
    },
    {
      id: 'sequential-runtime:invalid-transition',
      containerId: 'sequential-runtime',
      priority: 85,
      lamp: 'red',
      action: 'repair',
      signals: ['invalid transition', 'invalid step', 'transition error', 'invalid sequence'],
      minScore: 1,
      learnTag: 'sequential-runtime.invalid-transition',
      nextAction: 'Fix invalid step sequence in runtime.',
    },
    {
      id: 'sequential-runtime:completed',
      containerId: 'sequential-runtime',
      priority: 80,
      lamp: 'green',
      action: 'continue',
      signals: ['completed', 'sequence complete', 'all steps done', 'runtime finished'],
      minScore: 1,
      learnTag: 'sequential-runtime.completed',
      nextAction: 'Sequential runtime completed successfully.',
    },
    {
      id: 'sequential-runtime:failed',
      containerId: 'sequential-runtime',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['step failed', 'runtime failed', 'sequence failed', 'execution failed'],
      minScore: 1,
      learnTag: 'sequential-runtime.failed',
      nextAction: 'Analyze failure and prepare retry or repair plan.',
    },
    {
      id: 'sequential-runtime:skipped',
      containerId: 'sequential-runtime',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['step skipped', 'skipped step', 'step bypassed', 'skipped'],
      minScore: 1,
      learnTag: 'sequential-runtime.skipped',
      nextAction: 'Review skipped steps and consider re-enabling if needed.',
    },
    {
      id: 'sequential-runtime:paused',
      containerId: 'sequential-runtime',
      priority: 50,
      lamp: 'yellow',
      action: 'review',
      signals: ['step paused', 'runtime paused', 'execution paused', 'waiting'],
      minScore: 1,
      learnTag: 'sequential-runtime.paused',
      nextAction: 'Resume paused runtime or investigate pause reason.',
    },
    {
      id: 'sequential-runtime:retry-available',
      containerId: 'sequential-runtime',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['retry available', 'can retry', 'retry possible', 'recoverable'],
      minScore: 1,
      learnTag: 'sequential-runtime.retry-available',
      nextAction: 'Retry failed step using available retry option.',
    },
    {
      id: 'sequential-runtime:timeout-warning',
      containerId: 'sequential-runtime',
      priority: 70,
      lamp: 'yellow',
      action: 'review',
      signals: ['step timeout', 'timeout warning', 'taking too long', 'slow progress'],
      minScore: 1,
      learnTag: 'sequential-runtime.timeout-warning',
      nextAction: 'Investigate slow step or increase timeout.',
    },

    // Mobile Workbench patterns
    {
      id: 'mobile-workbench:active-work',
      containerId: 'mobile-workbench',
      priority: 90,
      lamp: 'green',
      action: 'continue',
      signals: ['active work', 'currently working', 'in progress', 'running'],
      minScore: 1,
      learnTag: 'mobile-workbench.active-work',
      nextAction: 'Follow active window and show matrix work view.',
    },
    {
      id: 'mobile-workbench:result-review',
      containerId: 'mobile-workbench',
      priority: 80,
      lamp: 'green',
      action: 'review',
      signals: ['result ready', 'result review', 'output ready', 'files ready'],
      minScore: 1,
      learnTag: 'mobile-workbench.result-review',
      nextAction: 'Show files and diff for review.',
    },
    {
      id: 'mobile-workbench:repo-setup',
      containerId: 'mobile-workbench',
      priority: 85,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['repo setup', 'repository setup', 'load repo', 'setup required'],
      minScore: 1,
      learnTag: 'mobile-workbench.repo-setup',
      nextAction: 'Open repo setup and request repository URL.',
    },
    {
      id: 'mobile-workbench:runtime-healthy',
      containerId: 'mobile-workbench',
      priority: 70,
      lamp: 'green',
      action: 'continue',
      signals: ['runtime healthy', 'checks green', 'system ok', 'runtime ready'],
      minScore: 1,
      learnTag: 'mobile-workbench.runtime-healthy',
      nextAction: 'System is healthy. Continue main flow.',
    },
    {
      id: 'mobile-workbench:real-stopper',
      containerId: 'mobile-workbench',
      priority: 95,
      lamp: 'red',
      action: 'repair',
      signals: ['real stopper', 'blocking error', 'critical blocker', 'stopper detected'],
      minScore: 1,
      learnTag: 'mobile-workbench.real-stopper',
      nextAction: 'Show repair or monitor view for blocker resolution.',
    },
    {
      id: 'mobile-workbench:awaiting-intent',
      containerId: 'mobile-workbench',
      priority: 50,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['awaiting intent', 'waiting for input', 'ready for goal', 'intent needed'],
      minScore: 1,
      learnTag: 'mobile-workbench.awaiting-intent',
      nextAction: 'Request user goal in simple language.',
    },
    {
      id: 'mobile-workbench:safe-fallback',
      containerId: 'mobile-workbench',
      priority: 1,
      lamp: 'yellow',
      action: 'review',
      signals: ['state unknown', 'cannot determine', 'fallback active', 'review needed'],
      minScore: 1,
      learnTag: 'mobile-workbench.safe-fallback',
      nextAction: 'Show safe fallback guidance and ask for clarification.',
    },
    {
      id: 'mobile-workbench:ready-to-start',
      containerId: 'mobile-workbench',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['ready to start', 'system ready', 'all set', 'prepared'],
      minScore: 1,
      learnTag: 'mobile-workbench.ready',
      nextAction: 'System is ready. Start new task or continue flow.',
    },
    {
      id: 'mobile-workbench:confirmation-needed',
      containerId: 'mobile-workbench',
      priority: 80,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['confirm action', 'please confirm', 'needs confirmation', 'awaiting approval'],
      minScore: 1,
      learnTag: 'mobile-workbench.confirmation',
      nextAction: 'Request user confirmation for action.',
    },
    {
      id: 'mobile-workbench:plan-mode',
      containerId: 'mobile-workbench',
      priority: 60,
      lamp: 'yellow',
      action: 'review',
      signals: ['plan mode', 'planning active', 'no execution', 'planning only'],
      minScore: 1,
      learnTag: 'mobile-workbench.plan-mode',
      nextAction: 'Currently in plan mode. Consider enabling execution.',
    },

    // Mobile Coach patterns
    {
      id: 'mobile-coach:working',
      containerId: 'mobile-coach',
      priority: 85,
      lamp: 'green',
      action: 'continue',
      signals: ['working', 'running', 'busy', 'in progress', 'is building'],
      minScore: 1,
      learnTag: 'mobile-coach.working',
      nextAction: 'Coach shows working state. No action needed from user.',
    },
    {
      id: 'mobile-coach:result-ready',
      containerId: 'mobile-coach',
      priority: 80,
      lamp: 'green',
      action: 'review',
      signals: ['result ready', 'output accepted', 'files ready', 'ready for review'],
      minScore: 1,
      learnTag: 'mobile-coach.result-ready',
      nextAction: 'Guide user to review files and diff.',
    },
    {
      id: 'mobile-coach:repo-needed',
      containerId: 'mobile-coach',
      priority: 85,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['repo fehlt', 'repo missing', 'no repo loaded', 'repository needed'],
      minScore: 1,
      learnTag: 'mobile-coach.repo-needed',
      nextAction: 'Guide user to open repo setup.',
    },
    {
      id: 'mobile-coach:stopper-detected',
      containerId: 'mobile-coach',
      priority: 90,
      lamp: 'red',
      action: 'repair',
      signals: ['stopper detected', 'blocking error', 'critical issue', 'error found'],
      minScore: 1,
      learnTag: 'mobile-coach.stopper-detected',
      nextAction: 'Guide user to repair view and next marked step.',
    },
    {
      id: 'mobile-coach:health-check',
      containerId: 'mobile-coach',
      priority: 70,
      lamp: 'green',
      action: 'continue',
      signals: ['checks healthy', 'runtime ok', 'validation passed', 'system green'],
      minScore: 1,
      learnTag: 'mobile-coach.health-check',
      nextAction: 'Health is good. User can continue main flow.',
    },
    {
      id: 'mobile-coach:idle',
      containerId: 'mobile-coach',
      priority: 50,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['waiting', 'idle', 'ready for input', 'what next'],
      minScore: 1,
      learnTag: 'mobile-coach.idle',
      nextAction: 'Ask user what they want to do next.',
    },
    {
      id: 'mobile-coach:error-recovered',
      containerId: 'mobile-coach',
      priority: 75,
      lamp: 'green',
      action: 'continue',
      signals: ['error recovered', 'issue fixed', 'problem resolved', 'back on track'],
      minScore: 1,
      learnTag: 'mobile-coach.recovered',
      nextAction: 'Error was recovered. Continue with workflow.',
    },
    {
      id: 'mobile-coach:learning-active',
      containerId: 'mobile-coach',
      priority: 60,
      lamp: 'green',
      action: 'continue',
      signals: ['learning active', 'pattern detected', 'improving', 'getting smarter'],
      minScore: 1,
      learnTag: 'mobile-coach.learning',
      nextAction: 'Self-learning is active. Pattern detected.',
    },
    {
      id: 'mobile-coach:help-needed',
      containerId: 'mobile-coach',
      priority: 80,
      lamp: 'yellow',
      action: 'ask-user',
      signals: ['need help', 'unsure', 'confused', 'not sure'],
      minScore: 1,
      learnTag: 'mobile-coach.help-needed',
      nextAction: 'Coach offers help options.',
    },
  ];
}

export const CONTAINER_INTELLIGENCE_PATTERN_RULES = buildPatternRules();

export function getPatternRulesForContainer(containerId: string): ContainerDecisionRule[] {
  return CONTAINER_INTELLIGENCE_PATTERN_RULES.filter((rule) => rule.containerId === containerId);
}

export function getPatternRuleById(ruleId: string): ContainerDecisionRule | undefined {
  return CONTAINER_INTELLIGENCE_PATTERN_RULES.find((rule) => rule.id === ruleId);
}

export function getAllContainerPatternRules(): ContainerDecisionRule[] {
  return [...CONTAINER_INTELLIGENCE_PATTERN_RULES];
}

export function getContainerIdsWithPatterns(): string[] {
  return [...new Set(CONTAINER_INTELLIGENCE_PATTERN_RULES.map((rule) => rule.containerId))];
}

export function assertContainerPatternRulesValid(): void {
  assertContainerDecisionRulesValid(CONTAINER_INTELLIGENCE_PATTERN_RULES);
  const ids = new Set<string>();
  for (const rule of CONTAINER_INTELLIGENCE_PATTERN_RULES) {
    if (ids.has(rule.id)) throw new Error(`Duplicate pattern rule id: ${rule.id}`);
    ids.add(rule.id);
  }
  for (const containerId of KNOWN_CONTAINER_IDS) {
    const rules = getPatternRulesForContainer(containerId);
    if (rules.length === 0) throw new Error(`No pattern rules defined for container: ${containerId}`);
  }
}