export type PromptCategory = 'analysis' | 'patch' | 'test' | 'docs' | 'security' | 'custom';
export interface PromptTemplate { readonly id: string; readonly label: string; readonly shortLabel: string; readonly category: PromptCategory; readonly prompt: string; readonly isBuiltin: boolean; readonly createdAt: number; readonly useCount: number; readonly lastUsedAt?: number; }
export interface PromptLibraryState { readonly version: 1; readonly customTemplates: readonly PromptTemplate[]; readonly savedAt: number; }
export const PROMPT_LIBRARY_STORAGE_KEY = 'sovereign-studio.prompt-library.v1';
export const BUILTIN_TEMPLATES: readonly PromptTemplate[] = [
  { id:'builtin-test',label:'Tests ausführen und Fehler erklären',shortLabel:'Tests',category:'test',isBuiltin:true,createdAt:0,useCount:0,prompt:'Führe die relevanten Tests im echten isolierten Workspace aus. Zeige Framework, Exit-Code, bestandene und fehlgeschlagene Tests. Bei Fehlern: analysiere die kausale Fehlerfamilie und bereite einen minimalen Fix mit Regressionstest als Draft PR vor. Kein Erfolg ohne echte Test-Evidence.' },
  { id:'builtin-review',label:'Code Review vor Draft PR',shortLabel:'Code Review',category:'analysis',isBuiltin:true,createdAt:0,useCount:0,prompt:'Prüfe den echten Workspace-Diff vor der Draft-PR-Erstellung auf Security-, Breaking-Change- und Qualitätsprobleme. HIGH-Findings blockieren. Keine erfundenen Findings und kein Review-Erfolg ohne aufgelöste OpenRouter- oder FreeLLM-Runtime-Evidence.' },
  { id:'builtin-security',label:'Security-Review durchführen',shortLabel:'Security',category:'security',isBuiltin:true,createdAt:0,useCount:0,prompt:'Analysiere das geladene Repository auf exponierte Secrets, unsichere Befehlsausführung, fehlende Autorisierung und unvalidierte Eingaben. Ordne Findings nach HIGH/MEDIUM/LOW mit Datei und Fundstelle. Nur belegte Findings.' },
  { id:'builtin-fix',label:'Fehler als Draft PR reparieren',shortLabel:'Fehler fixen',category:'patch',isBuiltin:true,createdAt:0,useCount:0,prompt:'Suche die belegte kausale Fehlerfamilie, erstelle einen minimalen Patch und einen Regressionstest. Prüfe Diff und Tests im isolierten Workspace und bereite ausschließlich einen Draft PR vor. Kein Auto-Merge.' },
  { id:'builtin-docs',label:'Dokumentation aktualisieren',shortLabel:'Dokumentation',category:'docs',isBuiltin:true,createdAt:0,useCount:0,prompt:'Vergleiche die reale Runtime- und API-Implementierung mit der Dokumentation. Aktualisiere nur nachweislich veraltete Abschnitte und kennzeichne unbelegte Zustände. Bereite die Änderungen als Draft PR vor.' },
  { id:'builtin-deps',label:'Abhängigkeiten prüfen',shortLabel:'Dependencies',category:'analysis',isBuiltin:true,createdAt:0,useCount:0,prompt:'Prüfe die vorhandenen Manifest- und Lock-Dateien auf veraltete oder riskante Abhängigkeiten. Schlage einen sicheren, kleinen Update-Pfad vor und führe passende Tests aus. Keine Major-Upgrades ohne klare Kompatibilitäts-Evidence.' },
  { id:'builtin-refactor',label:'Refactoring-Plan erstellen',shortLabel:'Refactoring',category:'analysis',isBuiltin:true,createdAt:0,useCount:0,prompt:'Analysiere das Repository auf Duplikate, überlange Funktionen, zirkuläre Abhängigkeiten und fehlende Fehlerbehandlung. Priorisiere nach Nutzen und Risiko. Nur Analyse, keine Mutation ohne bestätigten Auftrag.' },
  { id:'builtin-feature',label:'Architekturpassende Features vorschlagen',shortLabel:'Features',category:'analysis',isBuiltin:true,createdAt:0,useCount:0,prompt:'Lese die reale Architektur und schlage nächste Features vor, die in vorhandene Runtime-, Evidence- und Draft-PR-Verträge passen. Sortiere nach Nutzerwirkung, Aufwand und Risiko. Keine vollständige Umstrukturierung.' },
];
export function createEmptyState(): PromptLibraryState { return { version: 1, customTemplates: [], savedAt: Date.now() }; }
function valid(value: unknown): value is PromptLibraryState { return Boolean(value && typeof value === 'object' && (value as Record<string, unknown>).version === 1 && Array.isArray((value as Record<string, unknown>).customTemplates)); }
export function loadPromptLibraryState(storage: Storage): PromptLibraryState { try { const raw = storage.getItem(PROMPT_LIBRARY_STORAGE_KEY); if (!raw) return createEmptyState(); const parsed = JSON.parse(raw) as unknown; return valid(parsed) ? parsed : createEmptyState(); } catch { return createEmptyState(); } }
function persist(storage: Storage, state: PromptLibraryState): void { storage.setItem(PROMPT_LIBRARY_STORAGE_KEY, JSON.stringify({ ...state, savedAt: Date.now() })); }
export function getAllTemplates(state: PromptLibraryState): readonly PromptTemplate[] { return [...BUILTIN_TEMPLATES, ...state.customTemplates].sort((a,b) => Number(b.lastUsedAt ?? 0) - Number(a.lastUsedAt ?? 0)); }
export function filterTemplates(templates: readonly PromptTemplate[], options: { category?: PromptCategory; query?: string } = {}): readonly PromptTemplate[] { const query = options.query?.trim().toLowerCase(); return templates.filter((item) => (!options.category || item.category === options.category) && (!query || `${item.label} ${item.shortLabel} ${item.prompt}`.toLowerCase().includes(query))); }
export function availableCategories(templates: readonly PromptTemplate[]): readonly PromptCategory[] { return Array.from(new Set(templates.map((item) => item.category))); }
export function categoryLabel(category: PromptCategory): string { return ({ analysis:'Analyse',patch:'Patch / PR',test:'Tests',docs:'Dokumentation',security:'Security',custom:'Eigenes' } as const)[category]; }
export function saveCustomTemplate(storage: Storage, state: PromptLibraryState, input: { label: string; prompt: string; category: PromptCategory }): { state: PromptLibraryState; template: PromptTemplate } { const template: PromptTemplate = { id:`custom-${Date.now()}`, label:input.label.trim().slice(0,80), shortLabel:input.label.trim().slice(0,24), category:input.category, prompt:input.prompt.trim(), isBuiltin:false, createdAt:Date.now(), useCount:0 }; const next: PromptLibraryState = { version:1, customTemplates:[...state.customTemplates,template], savedAt:Date.now() }; persist(storage,next); return { state:next,template }; }
export function deleteCustomTemplate(storage: Storage, state: PromptLibraryState, id: string): PromptLibraryState { const next: PromptLibraryState = { ...state, customTemplates:state.customTemplates.filter((item) => item.id !== id), savedAt:Date.now() }; persist(storage,next); return next; }
export function markTemplateUsed(storage: Storage, state: PromptLibraryState, id: string): PromptLibraryState { if (BUILTIN_TEMPLATES.some((item) => item.id === id)) return state; const next: PromptLibraryState = { ...state, customTemplates:state.customTemplates.map((item) => item.id === id ? { ...item, useCount:item.useCount + 1,lastUsedAt:Date.now() } : item), savedAt:Date.now() }; persist(storage,next); return next; }
