#!/bin/bash
set -e

# Wait for device to be ready
adb wait-for-device

# Install the built APK
adb install -r android/app/build/outputs/apk/debug/app-debug.apk

# Clear existing logs
adb logcat -c

# Capture error logs in background
adb logcat *:E > emulator_error.log 2>&1 &
LOGCAT_PID=$!

echo "Starting Ghost Pilot sequence..."
# test_sequence.sh is generated by the previous step
if [ -f test_sequence.sh ]; then
  chmod +x test_sequence.sh
  bash test_sequence.sh || true
else
  echo "⚠️ test_sequence.sh not found, skipping execution"
fi

# Give the app some time to finish logging
sleep 5

# Stop log capture
if [ -n "$LOGCAT_PID" ]; then
  kill "$LOGCAT_PID" || true
fi

echo "=== ERROR SCAN ==="
if [ -f emulator_error.log ]; then
  if grep -Ei "ErrorBoundary|FATAL EXCEPTION|AndroidRuntime|RuntimeError|CRASH|com\.facebook\.react" emulator_error.log; then
    echo "❌ App fatal runtime error detected"
    grep -Ei "ErrorBoundary|FATAL EXCEPTION|AndroidRuntime|RuntimeError|CRASH|com\.facebook\.react" emulator_error.log | head -n 40
    exit 1
  fi

  if grep -Ei "ANR in com\.arestudio\.nocode\.aab" emulator_error.log; then
    echo "❌ App ANR detected"
    grep -Ei "ANR in com\.arestudio\.nocode\.aab" emulator_error.log | head -n 40
    exit 1
  fi
else
  echo "⚠️ emulator_error.log not found"
fi

echo "✅ No critical app crash detected"
