import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { expect, test, type APIRequestContext } from '@playwright/test';

/**
 * Read-only live endpoint smoke for the production frontend contract.
 * Static ownership is generated by scripts/frontend_endpoint_assurance.py.
 * This suite performs GET only and never promotes a passing probe to effect truth.
 */
const LIVE_ENDPOINT_SMOKE = process.env.SOVEREIGN_ENDPOINT_LIVE_SMOKE === '1';
const BACKEND_BASE = (process.env.VITE_ADMIN_API_BASE || '').replace(/\/+$/, '');
const ASSURANCE_REPORT = resolve(process.cwd(), '.security-reports/frontend-endpoint-assurance.json');

type AssuranceReference = { readonly normalized?: unknown; readonly classification?: unknown };
type AssuranceReport = { readonly status?: unknown; readonly references?: unknown };
type Probe = { readonly path: string; readonly allowedStatuses: readonly number[]; readonly family: string };

function target(path: string): string {
  if (!/^https:\/\//.test(BACKEND_BASE)) throw new Error('frontend_endpoint_https_backend_required');
  return `${BACKEND_BASE}${path.startsWith('/') ? path : `/${path}`}`;
}

function staticInternalEndpoints(): readonly string[] {
  if (!LIVE_ENDPOINT_SMOKE) return [];
  if (!existsSync(ASSURANCE_REPORT)) throw new Error('frontend_endpoint_assurance_report_missing');
  const report = JSON.parse(readFileSync(ASSURANCE_REPORT, 'utf8')) as AssuranceReport;
  if (report.status !== 'PASS' || !Array.isArray(report.references)) {
    throw new Error('frontend_endpoint_assurance_report_not_passed');
  }
  const endpoints = report.references
    .filter((item): item is AssuranceReference => Boolean(item && typeof item === 'object'))
    .filter((item) => item.classification === 'ACTIVE_INTERNAL')
    .map((item) => typeof item.normalized === 'string' ? item.normalized : '')
    .filter((endpoint) => endpoint.startsWith('/api/') && !endpoint.includes('<p>'));
  return [...new Set(endpoints)].sort();
}

const STATIC_INTERNAL_ENDPOINTS = staticInternalEndpoints();

const PROBES: readonly Probe[] = [
  { path: '/api/llm/routes', allowedStatuses: [200, 401, 403], family: 'llm-routing' },
  { path: '/api/billing', allowedStatuses: [200, 401, 403], family: 'billing' },
  { path: '/api/billing/credits', allowedStatuses: [200, 401, 403, 409], family: 'billing-credits' },
  { path: '/api/toolchain/universal/status', allowedStatuses: [200, 401, 403], family: 'toolchain' },
  { path: '/api/user/agent/jobs?limit=1', allowedStatuses: [200, 401, 403], family: 'agent-runtime' },
  { path: '/api/knowledge/stats', allowedStatuses: [200, 401, 403], family: 'knowledge' },
  { path: '/api/security/overview', allowedStatuses: [200, 401, 403], family: 'security' },
  { path: '/api/github-app/configured', allowedStatuses: [200, 401, 403, 503], family: 'github-app-config' },
] as const;

async function getReadOnly(request: APIRequestContext, path: string) {
  return request.get(target(path), {
    failOnStatusCode: false,
    maxRedirects: 0,
    headers: {
      Accept: 'application/json',
      'X-Sovereign-E2E-Probe': 'frontend-endpoint-readonly-v1',
    },
  });
}

async function assertReadOnlyRouteReachability(request: APIRequestContext, path: string): Promise<void> {
  const response = await getReadOnly(request, path);
  const status = response.status();
  expect(status >= 300 && status < 400, `${path} must not redirect an API probe`).toBe(false);
  expect(status, `${path} is missing from the live target`).not.toBe(404);
  expect(status, `${path} returned a server error`).toBeLessThan(500);
  if (status !== 405) {
    const contentType = (response.headers()['content-type'] || '').toLowerCase();
    expect(contentType, `${path} must keep non-405 API responses inside JSON`).toContain('application/json');
  }
}

async function assertReadOnlyJsonBoundary(request: APIRequestContext, probe: Probe): Promise<void> {
  const response = await getReadOnly(request, probe.path);
  const status = response.status();
  expect(probe.allowedStatuses, `${probe.family} returned unexpected HTTP ${status}`).toContain(status);
  expect(status, `${probe.family} must never hide a missing route behind 404`).not.toBe(404);
  expect(status >= 300 && status < 400, `${probe.family} must not redirect`).toBe(false);
  const contentType = (response.headers()['content-type'] || '').toLowerCase();
  expect(contentType, `${probe.family} must preserve the API JSON boundary`).toContain('application/json');
  const body = await response.text();
  expect(body.length, `${probe.family} returned an empty API body`).toBeGreaterThan(0);
  expect(body.length, `${probe.family} returned an unexpectedly large API body`).toBeLessThan(2_000_000);
  expect(() => JSON.parse(body), `${probe.family} returned invalid JSON`).not.toThrow();
}

test.describe('Frontend endpoint live runtime smoke', () => {
  test.skip(!LIVE_ENDPOINT_SMOKE, 'Enable explicitly after deployment with SOVEREIGN_ENDPOINT_LIVE_SMOKE=1.');

  test('built chat-first frontend loads before endpoint probes', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator('[data-testid="sovereign-chat-app"]')).toBeVisible({ timeout: 30_000 });
    await expect(page.locator('[data-testid="sovereign-chat-primary"]')).toBeVisible();
    await expect(page.locator('[data-testid="sovereign-chat-body-window"]')).toBeVisible();
    await expect(page.locator('[data-testid="live-workspace-monitor-desktop"]')).toHaveCount(0);
  });

  test('static assurance contributes exhaustive exact endpoints', async () => {
    expect(STATIC_INTERNAL_ENDPOINTS.length).toBeGreaterThan(0);
  });

  for (const endpoint of STATIC_INTERNAL_ENDPOINTS) {
    test(`static route: ${endpoint}`, async ({ request }) => {
      await assertReadOnlyRouteReachability(request, endpoint);
    });
  }

  for (const probe of PROBES) {
    test(`${probe.family}: ${probe.path}`, async ({ request }) => {
      await assertReadOnlyJsonBoundary(request, probe);
    });
  }
});
