/**
 * Predictive Coding Layer - Core Type Definitions
 *
 * Types for the biologically-inspired predictive coding system that generates
 * Top-Down predictions, computes prediction errors, and autonomously adapts
 * synaptic weights.
 *
 * Mathematical Foundation:
 * - Bottom-Up Signal: x(t) = actual runtime state
 * - Top-Down Prediction: x̂(t) = f(Ŵ · φ(t-1))
 * - Prediction Error: ε(t) = x(t) - x̂(t)
 * - Hebbian Weight Update: ΔW = η · ε(t) · ∂x̂(t)/∂W
 *
 * @module predictive/types
 */

// ============================================================================
// Core Signal Types
// ============================================================================

export type TraceId = string;

/**
 * Micro-signal emitted when runtime state changes.
 * Captures the raw sensory input from the runtime environment.
 */
export interface Signal {
  /** Unique identifier for the signal */
  id: string;
  /** Name of the node that emitted this signal */
  node: string;
  /** Numeric value representing the signal state */
  value: number;
  /** Unix timestamp in milliseconds */
  timestamp: number;
  /** Trace context for debugging */
  traceId: TraceId;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Top-Down prediction generated by the predictive layer.
 * Represents the system's expectation of what the bottom-up signal should be.
 */
export interface Prediction {
  /** Unique identifier for this prediction */
  id: string;
  /** The predicted value x̂(t) */
  predictedValue: number;
  /** Confidence score [0, 1] based on pattern match quality */
  confidence: number;
  /** The node this prediction is for */
  node: string;
  /** Timestamp when prediction was generated */
  timestamp: number;
  /** Trace context for debugging */
  traceId: TraceId;
  /** Reference to the pattern used for prediction */
  patternId?: string;
  /** The latent space embedding used for this prediction */
  embedding?: number[];
}

/**
 * Prediction error computed as the difference between actual and predicted.
 * Only signals with error above threshold propagate through the network.
 */
export interface PredictionError {
  /** Unique identifier for this error */
  id: string;
  /** Actual value x(t) */
  actual: number;
  /** Predicted value x̂(t) */
  predicted: number;
  /** Error value ε(t) = actual - predicted */
  error: number;
  /** Absolute error magnitude */
  absoluteError: number;
  /** Whether this error exceeds the propagation threshold */
  propagated: boolean;
  /** The node this error occurred on */
  node: string;
  /** Timestamp */
  timestamp: number;
  /** Trace context */
  traceId: TraceId;
  /** Weight of this error for learning */
  weight: number;
}

// ============================================================================
// Synaptic & Network Types
// ============================================================================

/**
 * Synaptic connection between two nodes.
 * Contains the adaptive weight that gets updated via Hebbian learning.
 */
export interface Synapse {
  /** Unique identifier for this synapse */
  id: string;
  /** Source node ID */
  sourceNode: string;
  /** Target node ID */
  targetNode: string;
  /** Current weight w ∈ [0, 1] */
  weight: number;
  /** Last update timestamp */
  lastUpdate: number;
  /** Number of successful co-activations */
  activationCount: number;
  /** Accumulated weight change for this epoch */
  weightDelta: number;
}

/**
 * Neural node representing a runtime state variable.
 * Each node maintains its own prediction and error history.
 */
export interface NeuralNode {
  /** Unique identifier for this node */
  id: string;
  /** Human-readable name */
  name: string;
  /** Current activation value */
  activation: number;
  /** Previous activation for temporal computation */
  previousActivation: number;
  /** Outgoing connections */
  outgoingSynapses: Synapse[];
  /** Incoming connections */
  incomingSynapses: Synapse[];
  /** Signal history for pattern matching */
  signalHistory: Signal[];
  /** Prediction history */
  predictionHistory: Prediction[];
  /** Error history */
  errorHistory: PredictionError[];
  /** Node type for categorization */
  nodeType: NodeType;
  /** Last activity timestamp */
  lastActivity: number;
}

/** Categories of neural nodes */
export type NodeType = 
  | 'sensor'      // Receives bottom-up signals
  | 'motor'       // Produces motor output
  | 'interneuron' // Intermediate processing
  | 'hidden';     // Internal representation

// ============================================================================
// Hebbian Learning Types
// ============================================================================

/**
 * Hebbian weight adaptation parameters.
 * Implements the learning rule: ΔW = η · ε(t) · ∂x̂(t)/∂W
 */
export interface HebbianConfig {
  /** Learning rate η (default: 0.01) */
  learningRate: number;
  /** Weight decay factor to prevent runaway growth */
  decayFactor: number;
  /** Maximum allowed weight */
  maxWeight: number;
  /** Minimum weight before pruning */
  minWeight: number;
  /** Damping factor to prevent oscillation */
  dampingFactor: number;
  /** Weight bounds for clamping */
  weightBounds: { min: number; max: number };
}

/**
 * Result of a Hebbian weight update operation.
 */
export interface WeightUpdateResult {
  /** Synapse that was updated */
  synapseId: string;
  /** Previous weight */
  previousWeight: number;
  /** New weight */
  newWeight: number;
  /** Change in weight */
  delta: number;
  /** Whether this was a growth or decay event */
  eventType: 'growth' | 'decay' | 'pruned';
  /** Confidence of this update based on error magnitude */
  confidence: number;
}

// ============================================================================
// Latent Space / Pattern Types
// ============================================================================

/**
 * Embedding vector for a signal pattern.
 * Used for cosine similarity search in the latent space.
 */
export interface PatternEmbedding {
  /** Unique identifier */
  id: string;
  /** Dense vector representation */
  embedding: number[];
  /** L2 norm of the embedding */
  norm: number;
  /** Associated signal value */
  signalValue: number;
  /** Node this pattern belongs to */
  node: string;
  /** Timestamp of creation */
  createdAt: number;
  /** Number of times this pattern was matched */
  matchCount: number;
  /** Average confidence when matched */
  avgConfidence: number;
}

/**
 * Result of a cosine similarity search.
 */
export interface SimilarityMatch {
  /** Matching pattern ID */
  patternId: string;
  /** Cosine similarity score [-1, 1] */
  score: number;
  /** Normalized score [0, 1] */
  normalizedScore: number;
  /** Pattern embedding */
  pattern: PatternEmbedding;
  /** Whether this is a strong match */
  isStrongMatch: boolean;
}

// ============================================================================
// Signal Processing Types
// ============================================================================

/**
 * Buffer for collecting signals before batch processing.
 * Uses a circular buffer to manage memory efficiently.
 */
export interface SignalBuffer {
  /** Buffer identifier */
  id: string;
  /** Collected signals */
  signals: Signal[];
  /** Maximum buffer size */
  maxSize: number;
  /** Oldest signal timestamp */
  oldestTimestamp: number;
  /** Newest signal timestamp */
  newestTimestamp: number;
  /** Whether buffer is full */
  isFull: boolean;
}

/**
 * Configuration for signal proxy interception.
 */
export interface SignalProxyConfig {
  /** Whether proxy is active */
  enabled: boolean;
  /** Signal batch size */
  batchSize: number;
  /** Flush interval in milliseconds */
  flushIntervalMs: number;
  /** Nodes to intercept */
  monitoredNodes: string[];
  /** Whether to intercept all nodes */
  interceptAll: boolean;
}

// ============================================================================
// Predictive Layer Types
// ============================================================================

/**
 * Configuration for the predictive layer.
 */
export interface PredictiveLayerConfig {
  /** Enable/disable the predictive layer */
  enabled: boolean;
  /** Hebbian learning parameters */
  hebbian: HebbianConfig;
  /** Signal processing parameters */
  signal: {
    batchSize: number;
    flushIntervalMs: number;
    maxBufferSize: number;
  };
  /** Latent space parameters */
  latentSpace: {
    dimension: number;
    maxPatterns: number;
    similarityThreshold: number;
  };
  /** Network topology */
  network: {
    maxConnectionsPerNode: number;
    correlationThreshold: number;
    synaptogenesisEnabled: boolean;
    pruningEnabled: boolean;
  };
  /** Error propagation */
  error: {
    threshold: number;
    propagationWeight: number;
  };
  /** Worker configuration */
  worker: {
    enabled: boolean;
    fallbackToMainThread: boolean;
  };
}

/**
 * State snapshot of the predictive layer.
 */
export interface PredictiveLayerSnapshot {
  /** Whether layer is active */
  active: boolean;
  /** Current phase */
  phase: 'idle' | 'predicting' | 'error-computing' | 'learning';
  /** Number of active nodes */
  nodeCount: number;
  /** Number of active synapses */
  synapseCount: number;
  /** Pattern count in latent space */
  patternCount: number;
  /** Average prediction confidence */
  avgConfidence: number;
  /** Error rate (errors above threshold / total) */
  errorRate: number;
  /** Memory usage estimate */
  memoryUsageBytes: number;
  /** Timestamp of snapshot */
  timestamp: number;
}

/**
 * Result of a full predictive coding cycle.
 */
export interface PredictiveCycleResult {
  /** Generated prediction */
  prediction: Prediction;
  /** Computed error */
  error: PredictionError;
  /** Weight updates applied */
  weightUpdates: WeightUpdateResult[];
  /** Latent space updates */
  latentSpaceUpdates: SimilarityMatch[];
  /** Whether prediction was accurate */
  predictionAccurate: boolean;
  /** Processing duration in milliseconds */
  durationMs: number;
}

// ============================================================================
// Telemetry Types
// ============================================================================

/**
 * Telemetry event for predictive layer operations.
 */
export interface PredictiveTelemetryEvent {
  /** Event name */
  name: string;
  /** Event properties */
  properties: Record<string, unknown>;
  /** Timestamp */
  timestamp: number;
  /** Trace ID */
  traceId: TraceId;
  /** Operation phase */
  phase: PredictiveLayerSnapshot['phase'];
}

/**
 * Performance metrics for predictive operations.
 */
export interface PredictiveMetrics {
  /** Average signal interception overhead */
  signalInterceptionMs: number;
  /** Average prediction generation time */
  predictionGenerationMs: number;
  /** Average error computation time */
  errorComputationMs: number;
  /** Average weight update time */
  weightUpdateMs: number;
  /** Average latent space search time */
  latentSpaceSearchMs: number;
  /** Total cycle time */
  totalCycleMs: number;
}

// ============================================================================
// Validation Schemas (Zod-like patterns for runtime validation)
// ============================================================================

/**
 * Runtime validation for Signal objects.
 */
export function isValidSignal(obj: unknown): obj is Signal {
  if (typeof obj !== 'object' || obj === null) return false;
  const s = obj as Partial<Signal>;
  return (
    typeof s.id === 'string' &&
    typeof s.node === 'string' &&
    typeof s.value === 'number' &&
    Number.isFinite(s.value) &&
    typeof s.timestamp === 'number' &&
    s.timestamp > 0 &&
    typeof s.traceId === 'string'
  );
}

/**
 * Runtime validation for Prediction objects.
 */
export function isValidPrediction(obj: unknown): obj is Prediction {
  if (typeof obj !== 'object' || obj === null) return false;
  const p = obj as Partial<Prediction>;
  return (
    typeof p.id === 'string' &&
    typeof p.predictedValue === 'number' &&
    Number.isFinite(p.predictedValue) &&
    typeof p.confidence === 'number' &&
    p.confidence >= 0 &&
    p.confidence <= 1 &&
    typeof p.node === 'string'
  );
}

/**
 * Runtime validation for Synapse objects.
 */
export function isValidSynapse(obj: unknown): obj is Synapse {
  if (typeof obj !== 'object' || obj === null) return false;
  const syn = obj as Partial<Synapse>;
  return (
    typeof syn.id === 'string' &&
    typeof syn.sourceNode === 'string' &&
    typeof syn.targetNode === 'string' &&
    typeof syn.weight === 'number' &&
    syn.weight >= 0 &&
    syn.weight <= 1
  );
}

// ============================================================================
// Default Configuration
// ============================================================================

export const DEFAULT_HEBBIAN_CONFIG: HebbianConfig = {
  learningRate: 0.01,
  decayFactor: 0.99,
  maxWeight: 1.0,
  minWeight: 0.05,
  dampingFactor: 0.9,
  weightBounds: { min: 0.0, max: 1.0 },
};

export const DEFAULT_PREDICTIVE_CONFIG: PredictiveLayerConfig = {
  enabled: true,
  hebbian: DEFAULT_HEBBIAN_CONFIG,
  signal: {
    batchSize: 10,
    flushIntervalMs: 10,
    maxBufferSize: 1000,
  },
  latentSpace: {
    dimension: 64,
    maxPatterns: 10000,
    similarityThreshold: 0.7,
  },
  network: {
    maxConnectionsPerNode: 10,
    correlationThreshold: 0.7,
    synaptogenesisEnabled: true,
    pruningEnabled: true,
  },
  error: {
    threshold: 0.1,
    propagationWeight: 1.0,
  },
  worker: {
    enabled: false, // Phase 2: Will be enabled after web worker is implemented
    fallbackToMainThread: true,
  },
};
