"""
Predictive signal pipeline module.
"""

from .signal_pipeline import (
    Signal,
    OrderedSignal,
    SignalOrderingError,
    TickWindowConfig,
    TickWindow,
    BackpressureState,
    DeterministicSignalPipeline,
    RecordedSignalSet,
    ReplayResult,
    FeatureVector,
    WindowReceipt,
    order_signals,
    process_signals_to_windows,
    replay_signals,
    canonical_sort,
    create_config_fingerprint,
    chunkwise,
    chunkwise_overlap,
    pairwise,
    group_by,
    running_difference,
    running_total,
    to_min_max,
)

__all__ = [
    "Signal",
    "OrderedSignal",
    "SignalOrderingError",
    "TickWindowConfig",
    "TickWindow",
    "BackpressureState",
    "DeterministicSignalPipeline",
    "RecordedSignalSet",
    "ReplayResult",
    "FeatureVector",
    "WindowReceipt",
    "order_signals",
    "process_signals_to_windows",
    "replay_signals",
    "canonical_sort",
    "create_config_fingerprint",
    "chunkwise",
    "chunkwise_overlap",
    "pairwise",
    "group_by",
    "running_difference",
    "running_total",
    "to_min_max",
]
