"""
Predictive module: signal pipeline and bounded action policy/readback contracts.
"""

from .signal_pipeline import (
    Signal,
    OrderedSignal,
    SignalOrderingError,
    TickWindowConfig,
    TickWindow,
    BackpressureState,
    DeterministicSignalPipeline,
    RecordedSignalSet,
    ReplayResult,
    FeatureVector,
    WindowReceipt,
    order_signals,
    process_signals_to_windows,
    replay_signals,
    canonical_sort,
    create_config_fingerprint,
    chunkwise,
    chunkwise_overlap,
    pairwise,
    group_by,
    running_difference,
    running_total,
    to_min_max,
)

__all__ = [
    "Signal",
    "OrderedSignal",
    "SignalOrderingError",
    "TickWindowConfig",
    "TickWindow",
    "BackpressureState",
    "DeterministicSignalPipeline",
    "RecordedSignalSet",
    "ReplayResult",
    "FeatureVector",
    "WindowReceipt",
    "order_signals",
    "process_signals_to_windows",
    "replay_signals",
    "canonical_sort",
    "create_config_fingerprint",
    "chunkwise",
    "chunkwise_overlap",
    "pairwise",
    "group_by",
    "running_difference",
    "running_total",
    "to_min_max",
]

from .action_policy import (
    ActionLevel,
    ActionPlan,
    CapabilityClass,
    LiveContext,
    PolicyDecision,
    PolicyVerdict,
    RejectReason,
    evaluate_plan,
    make_plan,
    normalize_parameters,
    payload_hash_for,
    can_derive,
    CONTRACT_VERSION,
)

from .causal_readback import (
    CausalVerdict,
    EvidenceWindow,
    ReadbackResult,
    evaluate_readback,
)

__all__ += [
    "ActionLevel",
    "ActionPlan",
    "CapabilityClass",
    "LiveContext",
    "PolicyDecision",
    "PolicyVerdict",
    "RejectReason",
    "evaluate_plan",
    "make_plan",
    "normalize_parameters",
    "payload_hash_for",
    "can_derive",
    "CONTRACT_VERSION",
    "CausalVerdict",
    "EvidenceWindow",
    "ReadbackResult",
    "evaluate_readback",
]
