import { describe, expect, it } from 'vitest';
import {
  DEFAULT_GITHUB_WRITE_PROXY_CONFIG,
  assertGitHubWriteProxyPayloadSafe,
  validateGitHubWriteProxyConfig,
  validateGitHubWriteProxyPayload,
} from './githubWriteProxyContract';

const safePayload = {
  repoUrl: 'https://github.com/OuroborosCollective/Sovereign-Studio-ato',
  title: 'Sovereign test draft',
  body: 'Generated by a backend write proxy.',
  operation: 'create_draft_pr' as const,
  files: [{ path: 'README.md', content: 'Safe documentation change.' }],
};

describe('githubWriteProxyContract', () => {
  it('requires a server-token proxy endpoint', () => {
    const report = validateGitHubWriteProxyConfig();

    expect(report.valid).toBe(true);
    expect(DEFAULT_GITHUB_WRITE_PROXY_CONFIG.requiresServerToken).toBe(true);
    expect(DEFAULT_GITHUB_WRITE_PROXY_CONFIG.endpointUrl).toBe('/api/github/draft-pr');
  });

  it('accepts safe draft PR payloads without a frontend token field', () => {
    const report = validateGitHubWriteProxyPayload(safePayload);

    expect(report.valid).toBe(true);
    expect(report.errors).toEqual([]);
    expect(() => assertGitHubWriteProxyPayloadSafe(safePayload)).not.toThrow();
  });

  it('rejects forbidden publish paths', () => {
    const report = validateGitHubWriteProxyPayload({
      ...safePayload,
      files: [{ path: '.env', content: 'SECRET=value' }],
    });

    expect(report.valid).toBe(false);
    expect(report.errors.join(' | ')).toContain('Forbidden file path');
  });

  it('rejects duplicate publish paths', () => {
    const report = validateGitHubWriteProxyPayload({
      ...safePayload,
      files: [
        { path: 'README.md', content: 'A' },
        { path: 'README.md', content: 'B' },
      ],
    });

    expect(report.valid).toBe(false);
    expect(report.errors.join(' | ')).toContain('Duplicate file path');
  });
});
