import { useMemo, useState, useCallback } from 'react';
import { FileItem, Card, WorkView, PipelineState, ProjectSettings, MobilePane } from '../types';
import { makeId, demoFiles, starterCards, defaultSettings } from '../constants';
import { syncApproval } from '../services/approvalSyncClient';

const sleep = (ms: number) => new Promise((resolve) => window.setTimeout(resolve, ms));

export function useProductMagic() {
  const [repoUrl, setRepoUrl] = useState('https://github.com/OuroborosCollective/Sovereign-Studio-ato');
  const [geminiKey, setGeminiKey] = useState('');
  const [blueprint, setBlueprint] = useState('Beschreibe deine Idee oder deinen Auftrag. Ich plane, generiere, pruefe und zeige alle Aenderungen sichtbar.');
  const [cards, setCards] = useState<Card[]>(starterCards());
  const [selectedFile, setSelectedFile] = useState<FileItem>(demoFiles[0]);
  const [built, setBuilt] = useState(false);
  const [chatInput, setChatInput] = useState('Starte mit diesem Auftrag.');
  const [logs, setLogs] = useState<string[]>(['Sovereign Studio bereit.', 'Links Auftrag und Dateien. Mitte Chat und Editor. Rechts nur Log.']);
  const [workView, setWorkView] = useState<WorkView>('editor');
  const [pipelineState, setPipelineState] = useState<PipelineState>('idle');
  const [fixLoops, setFixLoops] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [settings, setSettings] = useState<ProjectSettings>(defaultSettings);
  const [generatedCode, setGeneratedCode] = useState('');
  const [isWorking, setIsWorking] = useState(false);
  const [agentMessage, setAgentMessage] = useState('Bereit. Gib links deinen Auftrag ein und starte dann Schritt 1.');
  const [progress, setProgress] = useState(0);
  const [mobilePane, setMobilePane] = useState<MobilePane>('auftrag');
  const [currentStepLabel, setCurrentStepLabel] = useState('');
  const [nextStepLabel, setNextStepLabel] = useState('');
  const [approvalConfirmed, setApprovalConfirmed] = useState(false);

  const currentCode = useMemo(() => generatedCode || `// ${selectedFile.path}\n// Sovereign Auto-Resolver Preview\n\nconst auftrag = ${JSON.stringify(blueprint, null, 2)};\n\nexport const generatedProduct = {\n  mode: 'chat-editor-live-status',\n  repo: '${repoUrl}',\n  steps: ${cards.length},\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  linter: '${settings.linter}',\n  freeRoute: ['mlvoca', 'pollinations', 'optional-user-keys'],\n  ready: ${built}\n};`, [generatedCode, selectedFile.path, blueprint, repoUrl, cards.length, settings.repoMode, settings.packageManager, settings.linter, built]);

  const generatedPackage = useMemo(() => JSON.stringify({ repoUrl, blueprint, cards, selectedFile: selectedFile.path, settings, generatedCode: currentCode, approvalConfirmed }, null, 2), [repoUrl, blueprint, cards, selectedFile, settings, currentCode, approvalConfirmed]);

  const log = (text: string) => setLogs((items) => {
    const deduped = items[0] === text ? items : [text, ...items];
    return deduped.slice(0, 18);
  });

  const guardBusy = () => {
    if (!isWorking) return false;
    log('Bitte warten: Ich arbeite noch aktiv am aktuellen Schritt.');
    return true;
  };

  const generateCodeInEditor = useCallback(() => {
    const pm = settings.packageManager === 'auto' ? 'detected-package-manager' : settings.packageManager;
    const lintCommand = settings.linter === 'biome' ? `${pm} biome check .` : settings.linter === 'eslint' ? `${pm} lint` : `${pm} lint || ${pm} format`;
    const installCommand = settings.repoMode === 'monorepo' ? `${pm} install --frozen-lockfile` : `${pm} install`;
    const code = `// Generated by Sovereign Studio\n// File: generated/sovereign-product/workflow.ts\n\nexport const projectProfile = {\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  installStrategy: '${settings.installStrategy}',\n  linter: '${settings.linter}',\n  specialization: ${JSON.stringify(settings.specialization)},\n  freeRoute: ['mlvoca', 'pollinations', 'optional-user-keys']\n};\n\nexport const safeCommands = {\n  install: '${installCommand}',\n  lint: '${lintCommand}',\n  test: '${pm} test',\n  build: '${pm} build'\n};\n\nexport const userFlow = {\n  left: 'GitHub Datei Baum und Auftrag',\n  center: 'Chat plus Matrix File Editor plus Live Status',\n  right: 'Nur History Log',\n  onError: 'wait-for-user-then-visible-fix',\n  onGreen: 'wait-for-external-target-link'\n};\n\nexport const productSteps = ${JSON.stringify(cards.map((card) => ({ title: card.title, task: card.body })), null, 2)};\n\nexport function runVisibleWorkflow() {\n  return {\n    status: 'ready-for-check',\n    auftrag: ${JSON.stringify(blueprint)},\n    next: 'workflow-check'\n  };\n}\n`;
    setSelectedFile({ path: 'generated/sovereign-product/workflow.ts', icon: 'GEN' });
    setGeneratedCode(code);
    setBuilt(true);
    setWorkView('editor');
  }, [settings, cards, blueprint]);

  const runAutonomousJob = useCallback(async () => {
    if (isWorking) return;
    
    setIsWorking(true);
    setApprovalConfirmed(false);
    setMobilePane('live');
    setWorkView('editor');
    setFixLoops(0);
    log('=== Auftrag gestartet ===');
    setAgentMessage('Ich arbeite aktiv an deinem Auftrag. Bitte warten.');
    setCurrentStepLabel('Planung und Code-Entwurf');
    setNextStepLabel('Pruefung');

    setPipelineState('planning');
    setProgress(10);
    await sleep(800);
    
    setPipelineState('generating');
    setProgress(25);
    generateCodeInEditor();
    await sleep(600);
    log('Schritt 1/5 fertig: Planung und Code-Entwurf sichtbar.');
    setAgentMessage('Schritt 1 fertig: Planung und Code-Entwurf stehen.');
    setCurrentStepLabel('Pruefung');
    setNextStepLabel('Fix bei Fehler');

    setPipelineState('validating');
    setProgress(45);
    setAgentMessage('Ich pruefe jetzt aktiv. Bitte warten, ich haenge nicht.');
    await sleep(1200);
    
    const shouldRunVisibleFix = settings.maxFixLoops > 0;
    if (shouldRunVisibleFix) {
      setPipelineState('failed');
      setProgress(60);
      log('Schritt 2/5 fertig: Pruefung fand Fehler. Fix ist jetzt freigegeben.');
      setAgentMessage('Pruefung fertig: Fehler gefunden. Ich arbeite weiter.');
      setCurrentStepLabel('Fix anwenden');
      setNextStepLabel('Erneute Pruefung');

      setPipelineState('fixing');
      setProgress(70);
      setAgentMessage('Ich wende jetzt einen sichtbaren Fix an. Bitte warten.');
      await sleep(800);
      
      const patched = `${currentCode}\n\n// VisibleFix 1: sequential repair applied\nexport const validationPatch = {\n  reason: 'visible workflow fix completed',\n  linter: '${settings.linter}',\n  packageManager: '${settings.packageManager}',\n  rerunRequired: true\n};\n`;
      setGeneratedCode(patched);
      setFixLoops(1);
      log('Schritt 3/5 fertig: Fix sichtbar angewendet.');
      setAgentMessage('Fix fertig. Ich starte automatisch die erneute Pruefung.');
      setCurrentStepLabel('Erneute Pruefung');
      setNextStepLabel('Freigabe');

      setPipelineState('revalidating');
      setProgress(88);
      setAgentMessage('Ich pruefe erneut. Bitte warten, ich arbeite aktiv.');
      await sleep(1000);
      
      setPipelineState('green');
      setProgress(100);
      log('Schritt 4/5 fertig: Erneute Pruefung gruen. Freigabe wartet auf Ziel-Link.');
      setAgentMessage('Alles gruen. Freigabe ist erst fertig, wenn ein Ziel-Link im Log steht.');
      setCurrentStepLabel('Freigabe wartet');
      setNextStepLabel('Ziel-Link');
    } else {
      setPipelineState('green');
      setProgress(100);
      log('Schritt 2/5 fertig: Pruefung gruen. Freigabe wartet auf Ziel-Link.');
      setAgentMessage('Alles gruen. Freigabe ist erst fertig, wenn ein Ziel-Link im Log steht.');
      setCurrentStepLabel('Freigabe wartet');
      setNextStepLabel('Ziel-Link');
    }

    setIsWorking(false);
    log('=== Auftrag wartet: Externer Ziel-Link fehlt noch ===');
  }, [isWorking, settings.maxFixLoops, settings.linter, settings.packageManager, generateCodeInEditor, currentCode]);

  const buildProduct = useCallback(() => {
    if (guardBusy()) return;
    setApprovalConfirmed(false);
    runAutonomousJob();
  }, [guardBusy, runAutonomousJob]);

  const addCard = () => setCards((items) => [...items, { id: makeId(), title: 'Notiz', body: blueprint }]);

  const sendChat = useCallback(() => {
    if (!chatInput.trim()) return;
    log(`Chat Auftrag: ${chatInput}`);
    setChatInput('');
    buildProduct();
  }, [chatInput, log, buildProduct]);

  const downloadPackage = () => {
    const blob = new Blob([generatedPackage], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sovereign-product-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const patchFromPipeline = useCallback(() => {
    if (guardBusy()) return;
    setApprovalConfirmed(false);
    if (pipelineState !== 'failed') {
      log('Fix wartet: Erst muss eine echte Pruefung einen Fehler melden.');
      setAgentMessage('Ich brauche zuerst ein Pruefergebnis. Starte Pruefen, dann kann ich gezielt fixen.');
      return;
    }
    
    const patched = `${currentCode}\n\n// VisibleFix ${fixLoops + 1}: manual repair applied\nexport const validationPatch = {\n  reason: 'manual workflow fix completed',\n  linter: '${settings.linter}',\n  packageManager: '${settings.packageManager}',\n  rerunRequired: true\n};\n`;
    setGeneratedCode(patched);
    setFixLoops((count) => count + 1);
    setWorkView('editor');
    setAgentMessage('Fix manuell angewendet. Bitte Pruefen druecken fuer den naechsten Schritt.');
    log('Manueller Fix angewendet. Bitte Pruefen druecken.');
  }, [guardBusy, pipelineState, currentCode, settings.linter, settings.packageManager, fixLoops]);

  const publishAndValidate = useCallback(() => {
    if (guardBusy()) return;
    setApprovalConfirmed(false);
    if (!built) {
      log('Pruefung blockiert: Starte zuerst den Auftrag.');
      setAgentMessage('Erst Auftrag starten. Danach pruefe ich Schritt fuer Schritt.');
      return;
    }
    if (pipelineState === 'idle') {
      runAutonomousJob();
      return;
    }
    
    setWorkView('editor');
    setPipelineState('validating');
    setAgentMessage('Ich pruefe jetzt Struktur, Typecheck, Tests und Build-Konzept. Bitte warten, ich arbeite aktiv.');
    setTimeout(() => {
      if (fixLoops < 1) {
        setPipelineState('failed');
        setAgentMessage('Pruefung fertig: Fehler gefunden. Naechster Schritt: Fix sichtbar anwenden.');
        log('Manuelle Pruefung: Fehler gefunden. Fix ist freigegeben.');
      } else {
        setPipelineState('green');
        setAgentMessage('Pruefung fertig: Alles gruen. Freigabe wartet auf Ziel-Link im Log.');
        setCurrentStepLabel('Freigabe wartet');
        setNextStepLabel('Ziel-Link');
        log('Manuelle Pruefung: gruen. Externer Ziel-Link fehlt noch.');
      }
    }, 1400);
  }, [guardBusy, built, pipelineState, runAutonomousJob, fixLoops]);

  const mergeWhenGreen = useCallback(async () => {
    if (guardBusy()) return;

    if (approvalConfirmed) {
      log('Freigabe war bereits bestaetigt.');
      setAgentMessage('Freigabe ist bereits bestaetigt.');
      return;
    }

    if (pipelineState !== 'green') {
      log('Freigabe blockiert: Erst muss die Pruefung gruen sein.');
      setAgentMessage('Ich darf erst schreiben, wenn die Pruefung gruen ist.');
      return;
    }

    setIsWorking(true);
    setApprovalConfirmed(false);
    setMobilePane('live');
    setCurrentStepLabel('Schreibe nach GitHub');
    setNextStepLabel('Branch und Pull Request');
    setAgentMessage('Freigabe erhalten. Ich schreibe jetzt Branch, Dateien und Pull Request.');

    try {
      const result = await syncApproval({
        repoUrl,
        workflowCode: currentCode,
        manifestJson: generatedPackage,
        blueprint,
      });

      setApprovalConfirmed(true);
      setCurrentStepLabel('Freigabe bestaetigt');
      setNextStepLabel('Fertig');
      setAgentMessage(`GitHub Sync erledigt: ${result.pullRequestUrl}`);
      log(`GitHub PR erstellt: ${result.pullRequestUrl}`);
      log(`GitHub Branch erstellt: ${result.branchName}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);

      setApprovalConfirmed(false);
      setCurrentStepLabel('Freigabe fehlgeschlagen');
      setNextStepLabel('Sync pruefen');
      setAgentMessage(`Noch nicht abgeschlossen: ${message}`);
      log(`Approval Sync Fehler: ${message}`);
    } finally {
      setIsWorking(false);
    }
  }, [
    guardBusy,
    approvalConfirmed,
    pipelineState,
    repoUrl,
    currentCode,
    generatedPackage,
    blueprint,
    log,
  ]);

  return {
    repoUrl, setRepoUrl,
    geminiKey, setGeminiKey,
    blueprint, setBlueprint,
    cards, setCards,
    selectedFile, setSelectedFile,
    built, setBuilt,
    chatInput, setChatInput,
    logs, setLogs,
    workView, setWorkView,
    pipelineState, setPipelineState,
    fixLoops, setFixLoops,
    showSettings, setShowSettings,
    settings, setSettings,
    generatedCode, setGeneratedCode,
    currentCode,
    generatedPackage,
    isWorking,
    agentMessage,
    progress,
    mobilePane, setMobilePane,
    currentStepLabel, setCurrentStepLabel,
    nextStepLabel, setNextStepLabel,
    approvalConfirmed,
    log,
    generateCodeInEditor,
    buildProduct,
    addCard,
    sendChat,
    downloadPackage,
    publishAndValidate,
    patchFromPipeline,
    mergeWhenGreen,
    runAutonomousJob
  };
}
