import { useMemo, useState } from 'react';
import { FileItem, Card, WorkView, PipelineState, ProjectSettings } from '../types';
import { makeId, demoFiles, starterCards, defaultSettings } from '../constants';

export function useProductMagic() {
  const [repoUrl, setRepoUrl] = useState('https://github.com/OuroborosCollective/Sovereign-Studio-ato');
  const [accessKey, setAccessKey] = useState('');
  const [geminiKey, setGeminiKey] = useState('');
  const [blueprint, setBlueprint] = useState('Beschreibe deine Idee oder deinen Auftrag. Ich plane, generiere, pruefe und zeige alle Aenderungen sichtbar.');
  const [cards, setCards] = useState<Card[]>(starterCards());
  const [selectedFile, setSelectedFile] = useState<FileItem>(demoFiles[0]);
  const [built, setBuilt] = useState(false);
  const [chatInput, setChatInput] = useState('Starte mit diesem Auftrag.');
  const [logs, setLogs] = useState<string[]>(['Sovereign Studio bereit.', 'Links Auftrag und Dateien. Mitte Chat und Editor. Rechts Analyse und Verlauf.']);
  const [workView, setWorkView] = useState<WorkView>('editor');
  const [pipelineState, setPipelineState] = useState<PipelineState>('idle');
  const [fixLoops, setFixLoops] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [settings, setSettings] = useState<ProjectSettings>(defaultSettings);
  const [generatedCode, setGeneratedCode] = useState('');

  const currentCode = useMemo(() => generatedCode || `// ${selectedFile.path}\n// Sovereign Auto-Resolver Preview\n\nconst auftrag = ${JSON.stringify(blueprint, null, 2)};\n\nexport const generatedProduct = {\n  mode: 'chat-editor-live-status',\n  repo: '${repoUrl}',\n  steps: ${cards.length},\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  linter: '${settings.linter}',\n  freeRoute: ['mlvoca', 'pollinations', 'optional-user-keys'],\n  ready: ${built}\n};`, [generatedCode, selectedFile.path, blueprint, repoUrl, cards.length, settings.repoMode, settings.packageManager, settings.linter, built]);

  const generatedPackage = useMemo(() => JSON.stringify({ repoUrl, blueprint, cards, selectedFile: selectedFile.path, settings, generatedCode: currentCode }, null, 2), [repoUrl, blueprint, cards, selectedFile, settings, currentCode]);

  const log = (text: string) => setLogs((items) => [text, ...items].slice(0, 18));

  const generateCodeInEditor = () => {
    const pm = settings.packageManager === 'auto' ? 'detected-package-manager' : settings.packageManager;
    const lintCommand = settings.linter === 'biome' ? `${pm} biome check .` : settings.linter === 'eslint' ? `${pm} lint` : `${pm} lint || ${pm} format`;
    const installCommand = settings.repoMode === 'monorepo' ? `${pm} install --frozen-lockfile` : `${pm} install`;
    const code = `// Generated by Sovereign Studio\n// File: generated/sovereign-product/workflow.ts\n\nexport const projectProfile = {\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  installStrategy: '${settings.installStrategy}',\n  linter: '${settings.linter}',\n  specialization: ${JSON.stringify(settings.specialization)},\n  freeRoute: ['mlvoca', 'pollinations', 'optional-user-keys']\n};\n\nexport const safeCommands = {\n  install: '${installCommand}',\n  lint: '${lintCommand}',\n  test: '${pm} test',\n  build: '${pm} build'\n};\n\nexport const userFlow = {\n  left: 'GitHub Datei Baum und Auftrag',\n  center: 'Chat plus Matrix File Editor plus Live Status',\n  right: 'History Log und Analyse',\n  onError: 'return-to-center-and-fix',\n  onGreen: 'wait-for-user-confirmation'\n};\n\nexport const productSteps = ${JSON.stringify(cards.map((card) => ({ title: card.title, task: card.body })), null, 2)};\n\nexport function runVisibleWorkflow() {\n  return {\n    status: 'ready-for-review',\n    auftrag: ${JSON.stringify(blueprint)},\n    next: 'analyze-workflows'\n  };\n}\n`;
    setSelectedFile({ path: 'generated/sovereign-product/workflow.ts', icon: 'GEN' });
    setGeneratedCode(code);
    setBuilt(true);
    setWorkView('editor');
    log('Auftrag uebernommen. Chat, Editor und Live-Status sind in der Mitte sichtbar.');
  };

  const buildProduct = () => {
    generateCodeInEditor();
    log('Planung und Generierung gestartet. Du kannst live zusehen.');
  };

  const addCard = () => setCards((items) => [...items, { id: makeId(), title: 'Notiz', body: blueprint }]);

  const sendChat = () => {
    if (!chatInput.trim()) return;
    log(`Auftrag verstanden: ${chatInput}`);
    setChatInput('');
    generateCodeInEditor();
  };

  const downloadPackage = () => {
    const blob = new Blob([generatedPackage], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sovereign-product-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const patchFromPipeline = () => {
    setPipelineState('patching');
    setWorkView('editor');
    const patched = `${currentCode}\n\n// AutoPatch ${fixLoops}: visible analysis fix\nexport const validationPatch = {\n  reason: 'workflow issue resolved by visible patch loop',\n  linter: '${settings.linter}',\n  packageManager: '${settings.packageManager}',\n  monorepoSafe: ${settings.repoMode === 'monorepo'},\n  rerunAnalysis: true\n};\n`;
    setGeneratedCode(patched);
    log('Fix wurde sichtbar in der Mitte erzeugt. Danach startet die Pruefung erneut.');
    window.setTimeout(() => publishAndValidate(), 500);
  };

  const publishAndValidate = () => {
    setWorkView('pipeline');
    setPipelineState('publishing');
    log('Analyse startet. Ich pruefe Struktur, Fehler und Workflows.');
    window.setTimeout(() => {
      setPipelineState('validating');
      log(`Pruefung laeuft mit ${settings.packageManager}/${settings.linter}.`);
    }, 450);
    window.setTimeout(() => {
      if (fixLoops < 1) {
        setPipelineState('failed');
        setFixLoops((count) => count + 1);
        log('Fehler gefunden. Ich springe zurueck in die Mitte und starte den Fix.');
        setWorkView('editor');
        window.setTimeout(() => patchFromPipeline(), 350);
      } else {
        setPipelineState('green');
        log('Alles gruen. Bitte bestaetigen, bevor geschrieben wird.');
      }
    }, 900);
  };

  const mergeWhenGreen = () => {
    if (pipelineState !== 'green') {
      log('Freigabe blockiert: erst gruene Pruefung abwarten.');
      return;
    }
    log('Freigabe bestaetigt. Schreibvorgang kann vorbereitet werden.');
  };

  return {
    repoUrl, setRepoUrl,
    accessKey, setAccessKey,
    geminiKey, setGeminiKey,
    blueprint, setBlueprint,
    cards, setCards,
    selectedFile, setSelectedFile,
    built, setBuilt,
    chatInput, setChatInput,
    logs, setLogs,
    workView, setWorkView,
    pipelineState, setPipelineState,
    fixLoops, setFixLoops,
    showSettings, setShowSettings,
    settings, setSettings,
    generatedCode, setGeneratedCode,
    currentCode,
    generatedPackage,
    log,
    generateCodeInEditor,
    buildProduct,
    addCard,
    sendChat,
    downloadPackage,
    publishAndValidate,
    patchFromPipeline,
    mergeWhenGreen
  };
}
