import { useMemo, useState } from 'react';
import { FileItem, Card, WorkView, PipelineState, ProjectSettings } from '../types';
import { makeId, demoFiles, starterCards, defaultSettings } from '../constants';

export function useProductMagic() {
  const [repoUrl, setRepoUrl] = useState('https://github.com/OuroborosCollective/Sovereign-Studio-ato');
  const [accessKey, setAccessKey] = useState('');
  const [geminiKey, setGeminiKey] = useState('');
  const [blueprint, setBlueprint] = useState('Beschreibe deine Idee oder deinen Auftrag. Ich plane, generiere, pruefe und zeige alle Aenderungen sichtbar.');
  const [cards, setCards] = useState<Card[]>(starterCards());
  const [selectedFile, setSelectedFile] = useState<FileItem>(demoFiles[0]);
  const [built, setBuilt] = useState(false);
  const [chatInput, setChatInput] = useState('Starte mit diesem Auftrag.');
  const [logs, setLogs] = useState<string[]>(['Sovereign Studio bereit.', 'Links Auftrag und Dateien. Mitte Chat und Editor. Rechts nur Log.']);
  const [workView, setWorkView] = useState<WorkView>('editor');
  const [pipelineState, setPipelineState] = useState<PipelineState>('idle');
  const [fixLoops, setFixLoops] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [settings, setSettings] = useState<ProjectSettings>(defaultSettings);
  const [generatedCode, setGeneratedCode] = useState('');
  const [isWorking, setIsWorking] = useState(false);
  const [agentMessage, setAgentMessage] = useState('Bereit. Gib links deinen Auftrag ein und starte dann Schritt 1.');
  const [progress, setProgress] = useState(0);

  const currentCode = useMemo(() => generatedCode || `// ${selectedFile.path}\n// Sovereign Auto-Resolver Preview\n\nconst auftrag = ${JSON.stringify(blueprint, null, 2)};\n\nexport const generatedProduct = {\n  mode: 'chat-editor-live-status',\n  repo: '${repoUrl}',\n  steps: ${cards.length},\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  linter: '${settings.linter}',\n  freeRoute: ['mlvoca', 'pollinations', 'optional-user-keys'],\n  ready: ${built}\n};`, [generatedCode, selectedFile.path, blueprint, repoUrl, cards.length, settings.repoMode, settings.packageManager, settings.linter, built]);

  const generatedPackage = useMemo(() => JSON.stringify({ repoUrl, blueprint, cards, selectedFile: selectedFile.path, settings, generatedCode: currentCode }, null, 2), [repoUrl, blueprint, cards, selectedFile, settings, currentCode]);

  const log = (text: string) => setLogs((items) => [text, ...items].slice(0, 18));

  const guardBusy = () => {
    if (!isWorking) return false;
    log('Bitte warten: Ich arbeite noch aktiv am aktuellen Schritt.');
    return true;
  };

  const finishAfter = (message: string, nextProgress: number, fn: () => void) => {
    setIsWorking(true);
    setAgentMessage(message);
    window.setTimeout(() => {
      fn();
      setProgress(nextProgress);
      setIsWorking(false);
    }, 1400);
  };

  const generateCodeInEditor = () => {
    const pm = settings.packageManager === 'auto' ? 'detected-package-manager' : settings.packageManager;
    const lintCommand = settings.linter === 'biome' ? `${pm} biome check .` : settings.linter === 'eslint' ? `${pm} lint` : `${pm} lint || ${pm} format`;
    const installCommand = settings.repoMode === 'monorepo' ? `${pm} install --frozen-lockfile` : `${pm} install`;
    const code = `// Generated by Sovereign Studio\n// File: generated/sovereign-product/workflow.ts\n\nexport const projectProfile = {\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  installStrategy: '${settings.installStrategy}',\n  linter: '${settings.linter}',\n  specialization: ${JSON.stringify(settings.specialization)},\n  freeRoute: ['mlvoca', 'pollinations', 'optional-user-keys']\n};\n\nexport const safeCommands = {\n  install: '${installCommand}',\n  lint: '${lintCommand}',\n  test: '${pm} test',\n  build: '${pm} build'\n};\n\nexport const userFlow = {\n  left: 'GitHub Datei Baum und Auftrag',\n  center: 'Chat plus Matrix File Editor plus Live Status',\n  right: 'Nur History Log',\n  onError: 'wait-for-user-then-visible-fix',\n  onGreen: 'wait-for-user-confirmation'\n};\n\nexport const productSteps = ${JSON.stringify(cards.map((card) => ({ title: card.title, task: card.body })), null, 2)};\n\nexport function runVisibleWorkflow() {\n  return {\n    status: 'ready-for-check',\n    auftrag: ${JSON.stringify(blueprint)},\n    next: 'workflow-check'\n  };\n}\n`;
    setSelectedFile({ path: 'generated/sovereign-product/workflow.ts', icon: 'GEN' });
    setGeneratedCode(code);
    setBuilt(true);
    setWorkView('editor');
  };

  const buildProduct = () => {
    if (guardBusy()) return;
    finishAfter('Ich plane und schreibe den sichtbaren Arbeitsentwurf. Bitte warte kurz, ich haenge nicht.', 25, () => {
      generateCodeInEditor();
      setPipelineState('publishing');
      setAgentMessage('Schritt 1 fertig: Planung und Code-Entwurf stehen. Naechster Schritt: Pruefen.');
      log('Schritt 1 fertig: Auftrag uebernommen und Code-Entwurf sichtbar.');
    });
  };

  const addCard = () => setCards((items) => [...items, { id: makeId(), title: 'Notiz', body: blueprint }]);

  const sendChat = () => {
    if (!chatInput.trim()) return;
    log(`Chat Auftrag: ${chatInput}`);
    setChatInput('');
    buildProduct();
  };

  const downloadPackage = () => {
    const blob = new Blob([generatedPackage], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sovereign-product-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const patchFromPipeline = () => {
    if (guardBusy()) return;
    if (pipelineState !== 'failed') {
      log('Fix wartet: Erst muss eine echte Pruefung einen Fehler melden.');
      setAgentMessage('Ich brauche zuerst ein Pruefergebnis. Starte Pruefen, dann kann ich gezielt fixen.');
      return;
    }
    finishAfter('Ich wende jetzt einen sichtbaren Fix an. Bitte warten, danach entscheidest du den naechsten Pruefschritt.', 75, () => {
      const patched = `${currentCode}\n\n// VisibleFix ${fixLoops + 1}: sequential repair applied\nexport const validationPatch = {\n  reason: 'visible workflow fix completed',\n  linter: '${settings.linter}',\n  packageManager: '${settings.packageManager}',\n  rerunRequiredByUser: true\n};\n`;
      setGeneratedCode(patched);
      setFixLoops((count) => count + 1);
      setPipelineState('patching');
      setWorkView('editor');
      setAgentMessage('Fix fertig. Ich starte nicht automatisch weiter. Bitte druecke Pruefen fuer den naechsten Schritt.');
      log('Schritt 3 fertig: Fix sichtbar angewendet. Naechster Schritt muss manuell gestartet werden.');
    });
  };

  const publishAndValidate = () => {
    if (guardBusy()) return;
    if (!built) {
      log('Pruefung blockiert: Starte zuerst den Auftrag.');
      setAgentMessage('Erst Auftrag starten. Danach pruefe ich Schritt fuer Schritt.');
      return;
    }
    setWorkView('editor');
    setPipelineState('validating');
    finishAfter('Ich pruefe jetzt Struktur, Typecheck, Tests und Build-Konzept. Bitte warten, ich arbeite aktiv.', fixLoops > 0 ? 100 : 50, () => {
      if (fixLoops < 1) {
        setPipelineState('failed');
        setAgentMessage('Pruefung fertig: Fehler gefunden. Naechster Schritt: Fix sichtbar anwenden.');
        log('Schritt 2 fertig: Pruefung fand Fehler. Fix ist jetzt freigegeben.');
      } else {
        setPipelineState('green');
        setAgentMessage('Pruefung fertig: Alles gruen. Naechster Schritt: Freigabe bestaetigen.');
        log('Schritt 4 fertig: Pruefung gruen. Freigabe wartet auf dich.');
      }
    });
  };

  const mergeWhenGreen = () => {
    if (guardBusy()) return;
    if (pipelineState !== 'green') {
      log('Freigabe blockiert: Erst muss die Pruefung gruen sein.');
      setAgentMessage('Ich darf erst schreiben, wenn die Pruefung gruen ist.');
      return;
    }
    setAgentMessage('Freigabe bestaetigt. GitHub-Schreiben ist bereit, bleibt aber sichtbar und kontrolliert.');
    log('Schritt 5 fertig: Freigabe bestaetigt. Schreibvorgang kann vorbereitet werden.');
  };

  return {
    repoUrl, setRepoUrl,
    accessKey, setAccessKey,
    geminiKey, setGeminiKey,
    blueprint, setBlueprint,
    cards, setCards,
    selectedFile, setSelectedFile,
    built, setBuilt,
    chatInput, setChatInput,
    logs, setLogs,
    workView, setWorkView,
    pipelineState, setPipelineState,
    fixLoops, setFixLoops,
    showSettings, setShowSettings,
    settings, setSettings,
    generatedCode, setGeneratedCode,
    currentCode,
    generatedPackage,
    isWorking,
    agentMessage,
    progress,
    log,
    generateCodeInEditor,
    buildProduct,
    addCard,
    sendChat,
    downloadPackage,
    publishAndValidate,
    patchFromPipeline,
    mergeWhenGreen
  };
}
