import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useProductMagic } from './useProductMagic';

const BASE_TIME = 1_700_000_000_000;

const localStorageMock = (() => {
  let store: Record<string, string> = {};
  return {
    getItem: vi.fn((key: string) => store[key] ?? null),
    setItem: vi.fn((key: string, value: string) => { store[key] = value; }),
    removeItem: vi.fn((key: string) => { delete store[key]; }),
    clear: vi.fn(() => { store = {}; }),
  };
})();

Object.defineProperty(window, 'localStorage', { value: localStorageMock, configurable: true });

describe('useProductMagic - deterministic sequential workflow', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(Date, 'now').mockReturnValue(BASE_TIME);
    localStorageMock.clear();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('starts in a stable idle state', () => {
    const { result } = renderHook(() => useProductMagic());

    expect(result.current.pipelineState).toBe('idle');
    expect(result.current.isWorking).toBe(false);
    expect(result.current.progress).toBe(0);
    expect(result.current.built).toBe(false);
    expect(result.current.logs[0]).toContain('bereit');
  });

  it('completes the direct green flow deterministically', async () => {
    const { result } = renderHook(() => useProductMagic());

    act(() => {
      result.current.setSettings((prev) => ({ ...prev, maxFixLoops: 0 }));
    });

    await act(async () => {
      await result.current.runAutonomousJob();
    });

    expect(result.current.pipelineState).toBe('green');
    expect(result.current.progress).toBe(100);
    expect(result.current.built).toBe(true);
    expect(result.current.generatedCode).toContain('Generated by Sovereign Studio');
    expect(result.current.currentStepLabel).toBe('Freigabe wartet');
    expect(result.current.nextStepLabel).toBe('Ziel-Link');
    expect(result.current.isWorking).toBe(false);
    expect(result.current.architectureAnalysis).not.toBeNull();
    expect(result.current.suggestions.length).toBeGreaterThan(0);
  });

  it('completes the visible repair loop deterministically', async () => {
    const { result } = renderHook(() => useProductMagic());

    act(() => {
      result.current.setSettings((prev) => ({ ...prev, maxFixLoops: 3 }));
    });

    await act(async () => {
      await result.current.runAutonomousJob();
    });

    expect(result.current.pipelineState).toBe('green');
    expect(result.current.progress).toBe(100);
    expect(result.current.fixLoops).toBe(1);
    expect(result.current.generatedCode).toContain('validationPatch');
    expect(result.current.logs.some((log) => log.includes('Fix sichtbar angewendet'))).toBe(true);
  });

  it('keeps a busy guard while a sequential job is active', async () => {
    const { result } = renderHook(() => useProductMagic());
    let runningJob: Promise<void> | undefined;

    act(() => {
      runningJob = result.current.runAutonomousJob();
    });

    expect(result.current.isWorking).toBe(true);
    expect(result.current.pipelineState).toBe('planning');

    act(() => {
      result.current.buildProduct();
    });

    expect(result.current.logs[0]).toContain('Bitte warten');

    await act(async () => {
      await runningJob;
    });
  });

  it('runs architecture analysis without live API timing', async () => {
    const { result } = renderHook(() => useProductMagic());

    await act(async () => {
      await result.current.runArchitectureAnalysis();
    });

    expect(result.current.isAnalyzing).toBe(false);
    expect(result.current.architectureAnalysis).not.toBeNull();
    expect(result.current.suggestions.length).toBeGreaterThan(0);
    expect(result.current.chatMessages.some((message) => message.content.includes('Architektur-Analyse'))).toBe(true);
  });

  it('adds chat messages and deterministic assistant responses', () => {
    const { result } = renderHook(() => useProductMagic());

    act(() => {
      result.current.sendChatMessage('hilfe');
    });

    expect(result.current.chatMessages.some((message) => message.role === 'user' && message.content === 'hilfe')).toBe(true);
    expect(result.current.chatMessages.some((message) => message.role === 'assistant' && message.content.includes('So nutzt du Sovereign Studio'))).toBe(true);
  });

  it('accepts one suggestion and turns it into a card', async () => {
    const { result } = renderHook(() => useProductMagic());

    await act(async () => {
      await result.current.runArchitectureAnalysis();
    });

    const suggestionId = result.current.suggestions[0].id;
    const initialCardCount = result.current.cards.length;

    act(() => {
      result.current.acceptSuggestion(suggestionId);
    });

    expect(result.current.suggestions[0].accepted).toBe(true);
    expect(result.current.cards.length).toBeGreaterThan(initialCardCount);
  });

  it('blocks approval before the workflow is green', async () => {
    const { result } = renderHook(() => useProductMagic());

    await act(async () => {
      await result.current.mergeWhenGreen();
    });

    expect(result.current.approvalConfirmed).toBe(false);
    expect(result.current.agentMessage).toContain('Pruefung gruen');
  });
});
