import React, { useEffect } from 'react';
import type { FileContentResult } from '../runtime/fileContentBrowserRuntime';
import { C } from './builderConstants';
export function FileContentPreviewSheet({ filePath, result, loading, onClose, onSendToChat }: { readonly filePath: string; readonly result: FileContentResult | null; readonly loading: boolean; readonly onClose: () => void; readonly onSendToChat?: (prompt: string) => void }) {
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown',handler); return () => document.removeEventListener('keydown',handler); },[onClose]);
  return <div role="dialog" aria-modal="true" aria-label={`Dateivorschau: ${filePath}`} data-testid="file-content-preview-sheet" onClick={onClose} style={{ position:'fixed',inset:0,zIndex:9999,background:'rgba(0,0,0,.66)',display:'flex',alignItems:'flex-end',justifyContent:'center' }}>
    <section onClick={(event) => event.stopPropagation()} style={{ width:'100%',maxWidth:760,maxHeight:'86vh',display:'flex',flexDirection:'column',background:C.surface,border:`1px solid ${C.border}`,borderRadius:'18px 18px 0 0',overflow:'hidden' }}>
      <header style={{ display:'flex',alignItems:'center',gap:8,padding:12,borderBottom:`1px solid ${C.border}` }}><code style={{ flex:1,color:C.sky,wordBreak:'break-all' }}>{filePath}</code>{result?.language && result.language !== 'unknown' ? <span style={{ fontSize:10,color:C.textMuted }}>{result.language}</span> : null}<button type="button" onClick={onClose} aria-label="Vorschau schließen" style={{ minWidth:44,minHeight:44,background:'transparent',border:'none',color:C.text }}>×</button></header>
      <div style={{ flex:1,overflow:'auto' }}>{loading ? <p style={{ padding:20,color:C.textMuted }}>Workspace-Datei wird gelesen…</p> : result?.status === 'loaded' ? <><div style={{ padding:'5px 12px',fontSize:10,color:C.textMuted,borderBottom:`1px solid ${C.border}` }}>{result.sizeBytes} Bytes · SHA-256 {result.sha || 'nicht geliefert'}{result.truncated ? ' · Vorschau gekürzt' : ''}</div><pre aria-label="Dateiinhalt" style={{ margin:0,padding:14,whiteSpace:'pre',overflowX:'auto',fontSize:11,lineHeight:1.55,color:C.text }}>{result.content}</pre></> : <div style={{ padding:24,textAlign:'center',color:C.amber }}><div style={{ fontSize:28 }}>⚠️</div><p>{result?.error || 'Datei konnte nicht gelesen werden.'}</p></div>}</div>
      {!loading && result?.status === 'loaded' && onSendToChat ? <footer style={{ padding:10,borderTop:`1px solid ${C.border}` }}><button type="button" onClick={() => onSendToChat(`Prüfe diese echte Workspace-Datei: \`${filePath}\`\n\n\`\`\`\n${result.content.slice(0,20000)}\n\`\`\``)} style={{ minHeight:44,padding:'8px 14px',borderRadius:9,border:`1px solid ${C.sky}`,background:`${C.sky}18`,color:C.sky,cursor:'pointer' }}>In Chat übernehmen</button></footer> : null}
    </section>
  </div>;
}
export default FileContentPreviewSheet;
