/**
 * Repo Insight Panel
 *
 * Displays suggestions generated by the RepoInsightEngine:
 * - Fixes (Fehler & Fixes)
 * - Stabilität (Stabilität & Runtime)
 * - Feature-Ideen (Feature-Ideen)
 * - Empfohlene nächste Aufgabe (Recommended next task)
 *
 * @module product/components/RepoInsightPanel
 */

import React from 'react';
import type {
  RepoInsightSuggestion,
  RepoInsightEngineOutput,
} from '../runtime/repoInsightEngine';

export type InsightLamp = 'green' | 'yellow' | 'red';

export interface RepoInsightPanelProps {
  output: RepoInsightEngineOutput | null;
  isLoading: boolean;
  onSuggestionClick: (suggestion: RepoInsightSuggestion) => void;
  onRecommendedMissionClick: (mission: string) => void;
}

const lampClass: Record<InsightLamp, string> = {
  green: 'bg-emerald-400 shadow-emerald-400/50',
  yellow: 'bg-amber-300 shadow-amber-300/50',
  red: 'bg-rose-400 shadow-rose-400/50',
};

const frameClass: Record<InsightLamp, string> = {
  green: 'border-emerald-400/35 bg-emerald-500/10',
  yellow: 'border-amber-400/35 bg-amber-500/10',
  red: 'border-rose-400/35 bg-rose-500/10',
};

const riskClass: Record<string, string> = {
  niedrig: 'text-emerald-400 bg-emerald-500/20 border border-emerald-500/30',
  mittel: 'text-amber-400 bg-amber-500/20 border border-amber-500/30',
  hoch: 'text-rose-400 bg-rose-500/20 border border-rose-500/30',
};

function SuggestionCard({
  suggestion,
  onClick,
}: {
  suggestion: RepoInsightSuggestion;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="w-full rounded-xl border border-slate-700/50 bg-slate-800/50 p-3 text-left transition-all hover:border-cyan-500/50 hover:bg-slate-800/80 focus:border-cyan-500/70 focus:outline-none focus:ring-2 focus:ring-cyan-500/30"
    >
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-sm font-bold text-white">{suggestion.title}</span>
        <span
          className={`rounded-full px-2 py-0.5 text-xs font-medium ${riskClass[suggestion.risk]}`}
        >
          {suggestion.risk}
        </span>
      </div>
      <p className="mt-1.5 text-xs leading-relaxed text-slate-300">
        {suggestion.whyUseful}
      </p>
      <div className="mt-2 flex flex-wrap items-center justify-between gap-2">
        <span className="text-xs text-slate-500">
          {suggestion.affectedFiles.slice(0, 2).join(', ')}
          {suggestion.affectedFiles.length > 2 && ` +${suggestion.affectedFiles.length - 2}`}
        </span>
        <span className="rounded-lg bg-cyan-500/20 px-2.5 py-1 text-xs font-bold text-cyan-300">
          {suggestion.actionLabel}
        </span>
      </div>
    </button>
  );
}

function InsightGroup({
  category,
  label,
  suggestions,
  onSuggestionClick,
  accentColor = 'cyan',
}: {
  category: string;
  label: string;
  suggestions: RepoInsightSuggestion[];
  onSuggestionClick: (suggestion: RepoInsightSuggestion) => void;
  accentColor?: string;
}) {
  if (suggestions.length === 0) {
    return null;
  }

  const accentClasses: Record<string, string> = {
    cyan: 'border-cyan-500/30 text-cyan-300',
    emerald: 'border-emerald-500/30 text-emerald-300',
    violet: 'border-violet-500/30 text-violet-300',
  };

  return (
    <div className="space-y-2">
      <h3 className={`flex items-center gap-2 border-b border-slate-700/50 pb-2 text-sm font-black uppercase tracking-wider ${accentClasses[accentColor] ?? accentClasses.cyan}`}>
        {label}
        <span className="rounded-full bg-slate-700/50 px-2 py-0.5 text-xs font-bold text-slate-400">
          {suggestions.length}
        </span>
      </h3>
      <div className="space-y-2">
        {suggestions.slice(0, 5).map((suggestion) => (
          <SuggestionCard
            key={suggestion.id}
            suggestion={suggestion}
            onClick={() => onSuggestionClick(suggestion)}
          />
        ))}
        {suggestions.length > 5 && (
          <p className="text-center text-xs text-slate-500">
            +{suggestions.length - 5} weitere Vorschläge
          </p>
        )}
      </div>
    </div>
  );
}

function compactMissionPreview(mission: string): string {
  const oneLine = mission.replace(/\s+/g, ' ').trim();
  return oneLine.length > 260 ? `${oneLine.slice(0, 257)}...` : oneLine;
}

function RecommendedMission({
  mission,
  confidence,
  onClick,
}: {
  mission: string;
  confidence: number;
  onClick: () => void;
}) {
  const confidenceColor =
    confidence >= 0.8
      ? 'text-emerald-400'
      : confidence >= 0.6
        ? 'text-amber-400'
        : 'text-slate-400';

  return (
    <div className="space-y-2">
      <h3 className="flex items-center gap-2 border-b border-slate-700/50 pb-2 text-sm font-black uppercase tracking-wider text-violet-300">
        Empfohlene nächste Aufgabe
        <span className={`text-xs font-bold ${confidenceColor}`}>
          {Math.round(confidence * 100)}% sicher
        </span>
      </h3>
      <button
        type="button"
        onClick={onClick}
        className="w-full rounded-xl border border-violet-500/30 bg-gradient-to-r from-violet-500/10 to-purple-500/10 p-4 text-left transition-all hover:border-violet-500/60 hover:from-violet-500/20 hover:to-purple-500/20 focus:border-violet-500/70 focus:outline-none focus:ring-2 focus:ring-violet-500/30"
      >
        <p className="sovereign-recommended-mission-text text-sm font-medium leading-relaxed text-white">{compactMissionPreview(mission)}</p>
        <div className="mt-3 flex flex-wrap items-center gap-2">
          <span className="rounded-lg bg-violet-500/30 px-3 py-1.5 text-xs font-bold text-violet-200">
            🚀 In Builder übernehmen
          </span>
          <span className="text-xs text-slate-500">
            Übernimmt den Auftrag ohne Kopieren
          </span>
        </div>
      </button>
    </div>
  );
}

function FindingsSummary({ output }: { output: RepoInsightEngineOutput }) {
  const detectedItems = output.findings.filter((f) => f.type === 'detected');
  const missingItems = output.findings.filter((f) => f.type === 'missing');

  return (
    <div className="mb-3 flex flex-wrap gap-2 rounded-lg bg-slate-900/50 p-2">
      {detectedItems.map((item, i) => (
        <span
          key={i}
          className="rounded bg-emerald-500/20 px-2 py-0.5 text-xs text-emerald-400"
        >
          ✓ {item.description}
        </span>
      ))}
      {missingItems.map((item, i) => (
        <span
          key={i}
          className="rounded bg-amber-500/20 px-2 py-0.5 text-xs text-amber-400"
        >
          ✗ {item.description}
        </span>
      ))}
    </div>
  );
}

export function RepoInsightPanel({
  output,
  isLoading,
  onSuggestionClick,
  onRecommendedMissionClick,
}: RepoInsightPanelProps) {
  if (isLoading) {
    return (
      <section className="mt-4 rounded-3xl border border-slate-700/50 bg-slate-900/50 p-4">
        <div className="flex items-center justify-center gap-3 py-8">
          <div className="h-5 w-5 animate-spin rounded-full border-2 border-cyan-500 border-t-transparent" />
          <span className="text-sm text-slate-400">Repository wird analysiert...</span>
        </div>
      </section>
    );
  }

  if (!output) {
    return (
      <section className="mt-4 rounded-3xl border border-slate-700/50 bg-slate-900/50 p-4">
        <div className="py-6 text-center">
          <span className="text-3xl">🤖</span>
          <p className="mt-2 text-sm text-slate-500">
            Lade ein Repository, um Vorschläge zu erhalten.
          </p>
        </div>
      </section>
    );
  }

  const coachLamp = output.coachStatus as InsightLamp;
  const hasSuggestions =
    output.fixSuggestions.length > 0 ||
    output.hardeningSuggestions.length > 0 ||
    output.featureSuggestions.length > 0;

  return (
    <section className={`sovereign-repo-insight-panel mt-4 space-y-4 rounded-3xl border p-4 ${frameClass[coachLamp]}`}>
      {/* Header */}
      <div className="flex flex-wrap items-center gap-3">
        <div
          className={`flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-300/30 bg-slate-950/70 text-xl shadow-lg shadow-cyan-950/30`}
          aria-hidden="true"
        >
          🤖
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span
              className={`h-3 w-3 rounded-full shadow-lg ${lampClass[coachLamp]}`}
              aria-label={`Status ${coachLamp}`}
            />
            <h2 className="font-black tracking-tight text-white">
              Vorschläge aus Repo-Analyse
            </h2>
          </div>
          <p className="mt-1 text-xs leading-relaxed text-slate-300">
            {output.coachMessage}
          </p>
        </div>
        <span className="rounded bg-slate-800 px-2 py-1 text-xs text-slate-400">
          {output.analyzedFiles} Dateien analysiert
        </span>
      </div>

      {/* Blockers Warning */}
      {output.blockers.length > 0 && (
        <div className="rounded-lg border border-rose-500/30 bg-rose-500/10 p-3">
          <p className="text-sm font-bold text-rose-400">
            ⚠️ Blocker erkannt
          </p>
          {output.blockers.map((blocker, i) => (
            <p key={i} className="mt-1 text-xs text-slate-300">
              {blocker.message}
            </p>
          ))}
        </div>
      )}

      {/* Findings Summary */}
      {output.findings.length > 0 && <FindingsSummary output={output} />}

      {/* Suggestions Grid */}
      {hasSuggestions ? (
        <div className="sovereign-insight-groups grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <InsightGroup
            category="fix"
            label="🔧 Fehler & Fixes"
            suggestions={output.fixSuggestions}
            onSuggestionClick={onSuggestionClick}
            accentColor="cyan"
          />
          <InsightGroup
            category="stabilitaet"
            label="🛡️ Stabilität & Runtime"
            suggestions={output.hardeningSuggestions}
            onSuggestionClick={onSuggestionClick}
            accentColor="emerald"
          />
          <InsightGroup
            category="feature"
            label="✨ Feature-Ideen"
            suggestions={output.featureSuggestions}
            onSuggestionClick={onSuggestionClick}
            accentColor="violet"
          />
        </div>
      ) : (
        <div className="py-4 text-center">
          <p className="text-sm text-slate-500">
            Keine spezifischen Vorschläge gefunden.
          </p>
          <p className="mt-1 text-xs text-slate-600">
            Die Analyse ist abgeschlossen.
          </p>
        </div>
      )}

      {/* Recommended Mission */}
      {output.recommendedMission && (
        <RecommendedMission
          mission={output.recommendedMission}
          confidence={output.recommendedMissionConfidence}
          onClick={() => onRecommendedMissionClick(output.recommendedMission)}
        />
      )}

      {/* Confidence Indicator */}
      <div className="flex items-center justify-between border-t border-slate-700/30 pt-3 text-xs text-slate-500">
        <span>
          Analyse-Vertrauen: {Math.round(output.confidence * 100)}%
        </span>
        <span>
          {output.fixSuggestions.length +
            output.hardeningSuggestions.length +
            output.featureSuggestions.length}{' '}
          Vorschläge generiert
        </span>
      </div>
    </section>
  );
}
