import React, { useState } from 'react';
import type { TestRunnerResult } from '../runtime/testRunnerRuntime';
import { C } from './builderConstants';
export function TestRunnerResultCard({ result, onRepair }: { readonly result: TestRunnerResult; readonly onRepair?: (prompt: string) => void }) {
  const [open, setOpen] = useState(false); const color = result.status === 'passed' ? C.green : result.status === 'failed' ? C.rose : C.amber; const icon = result.status === 'passed' ? '✅' : result.status === 'failed' ? '❌' : '⚠️';
  return <article role="region" aria-label="Test-Runner Ergebnis" data-testid="test-runner-result-card" style={{ margin:'8px 12px',padding:12,borderRadius:12,border:`1px solid ${color}55`,background:`${color}0d` }}>
    <div style={{ display:'flex',alignItems:'center',gap:8 }}><span aria-hidden="true">{icon}</span><strong style={{ color }}>{result.status === 'passed' ? 'Tests bestanden' : result.status === 'failed' ? 'Tests fehlgeschlagen' : 'Test-Runner blockiert'}</strong>{result.framework !== 'unknown' ? <code style={{ marginLeft:'auto',color:C.textMuted }}>{result.framework}</code> : null}</div>
    <p style={{ color:C.textSub,fontSize:12 }}>{result.summary}</p>
    {(result.counts.passed + result.counts.failed + result.counts.errors + result.counts.skipped) > 0 ? <div role="list" aria-label="Test-Statistik" style={{ display:'flex',gap:8,flexWrap:'wrap',fontSize:11 }}><span role="listitem" style={{ color:C.green }}>{result.counts.passed} bestanden</span><span role="listitem" style={{ color:C.rose }}>{result.counts.failed} fehlgeschlagen</span><span role="listitem" style={{ color:C.amber }}>{result.counts.errors} Fehler</span><span role="listitem" style={{ color:C.textMuted }}>{result.counts.skipped} übersprungen</span></div> : null}
    {result.blocker ? <p style={{ color:C.amber,fontSize:11 }}>{result.blocker}</p> : null}
    {result.output ? <><button type="button" aria-expanded={open} aria-controls="test-runner-output" aria-label={open ? 'Echte Test-Ausgabe ausblenden' : 'Echte Test-Ausgabe anzeigen'} title={open ? 'Echte Test-Ausgabe ausblenden' : 'Echte Test-Ausgabe anzeigen'} onClick={() => setOpen((value) => !value)} className="focus-visible:ring-2 focus-visible:ring-sky-500 focus-visible:outline-none rounded px-1.5 py-0.5 transition-opacity hover:opacity-80" style={{ marginTop:8,background:'transparent',border:'none',color:C.sky,cursor:'pointer' }}>{open ? 'Ausgabe schließen' : 'Echte Test-Ausgabe anzeigen'}</button>{open ? <pre id="test-runner-output" tabIndex={0} aria-label="Test-Runner Ausgabe-Protokoll" className="focus-visible:ring-2 focus-visible:ring-sky-500 focus-visible:outline-none rounded" style={{ maxHeight:280,overflow:'auto',whiteSpace:'pre-wrap',fontSize:10,padding:10,background:C.bg,border:`1px solid ${C.border}`,color:C.text }}>{result.output}</pre> : null}</> : null}
    {result.hasRepairHint && onRepair ? <button type="button" aria-label="Fehlgeschlagene Tests reparieren" title="Fehlgeschlagene Tests mit Reparatur-Mission im Builder beheben" onClick={() => onRepair(`Repariere die fehlgeschlagenen ${result.framework === 'unknown' ? '' : `${result.framework}-`}Tests aus der belegten Ausgabe. Erzeuge einen minimalen Fix mit Regressionstest und bereite nur einen Draft PR vor.\n\n${result.output.slice(0,6000)}`)} className="focus-visible:ring-2 focus-visible:ring-rose-500 focus-visible:outline-none transition-opacity hover:opacity-90" style={{ marginTop:10,minHeight:44,padding:'8px 14px',borderRadius:9,border:`1px solid ${C.rose}`,background:`${C.rose}18`,color:C.rose,cursor:'pointer' }}>🛠 Reparieren</button> : null}
  </article>;
}
export default TestRunnerResultCard;
