import React, { useMemo, useState } from 'react';
import { FileItem, Card, WorkView, PipelineState, ProjectSettings } from './features/product/types';
import { makeId, demoFiles, starterCards, defaultSettings } from './features/product/constants';
import { AlertTriangle, Bot, CheckCircle, Code2, Download, Eye, FolderTree, Plus, RefreshCw, Rocket, Send, Settings, Shield, Sparkles, Trash2, Wand2 } from 'lucide-react';



export default function ProductMagicApp() {
  const [repoUrl, setRepoUrl] = useState('https://github.com/OuroborosCollective/Wasd');
  const [accessKey, setAccessKey] = useState('');
  const [geminiKey, setGeminiKey] = useState('');
  const [blueprint, setBlueprint] = useState('Baue aus diesem Workflow eine klickbare Mini-App mit GitHub Explorer, Auto-Resolver, Living Preview und Agent Workspace.');
  const [cards, setCards] = useState<Card[]>(starterCards());
  const [selectedFile, setSelectedFile] = useState<FileItem>(demoFiles[0]);
  const [built, setBuilt] = useState(false);
  const [chatInput, setChatInput] = useState('Setze diesen Workflow als echtes Produkt um.');
  const [logs, setLogs] = useState<string[]>(['🚀 NOCode Studio Auto-Resolver geladen.']);
  const [workView, setWorkView] = useState<WorkView>('editor');
  const [pipelineState, setPipelineState] = useState<PipelineState>('idle');
  const [fixLoops, setFixLoops] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [settings, setSettings] = useState<ProjectSettings>(defaultSettings);
  const [generatedCode, setGeneratedCode] = useState('');

  const currentCode = generatedCode || `// ${selectedFile.path}\n// Sovereign Auto-Resolver Preview\n\nconst blueprint = ${JSON.stringify(blueprint, null, 2)};\n\nexport const generatedProduct = {\n  mode: 'living-preview',\n  repo: '${repoUrl}',\n  modules: ${cards.length},\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  linter: '${settings.linter}',\n  ready: ${built}\n};`;

  const generatedPackage = useMemo(() => JSON.stringify({ repoUrl, blueprint, cards, selectedFile: selectedFile.path, settings, generatedCode: currentCode }, null, 2), [repoUrl, blueprint, cards, selectedFile, settings, currentCode]);

  const log = (text: string) => setLogs((items) => [text, ...items].slice(0, 14));

  const generateCodeInEditor = () => {
    const pm = settings.packageManager === 'auto' ? 'detected-package-manager' : settings.packageManager;
    const lintCommand = settings.linter === 'biome' ? `${pm} biome check .` : settings.linter === 'eslint' ? `${pm} lint` : `${pm} lint || ${pm} format`;
    const installCommand = settings.repoMode === 'monorepo' ? `${pm} install --frozen-lockfile` : `${pm} install`;
    const code = `// Generated by NOCode Studio\n// File: generated/sovereign-product/workflow.ts\n\nexport const projectProfile = {\n  repoMode: '${settings.repoMode}',\n  packageManager: '${settings.packageManager}',\n  installStrategy: '${settings.installStrategy}',\n  linter: '${settings.linter}',\n  specialization: ${JSON.stringify(settings.specialization)}\n};\n\nexport const safeCommands = {\n  install: '${installCommand}',\n  lint: '${lintCommand}',\n  test: '${pm} test',\n  build: '${pm} build'\n};\n\nexport const productModules = ${JSON.stringify(cards.map((card) => ({ title: card.title, task: card.body })), null, 2)};\n\nexport function runVisibleWorkflow() {\n  return {\n    status: 'ready-for-review',\n    blueprint: ${JSON.stringify(blueprint)},\n    next: 'publish-and-validate'\n  };\n}\n`;
    setSelectedFile({ path: 'generated/sovereign-product/workflow.ts', icon: '✨' });
    setGeneratedCode(code);
    setBuilt(true);
    setWorkView('editor');
    log('💻 Code-Agent schreibt jetzt sichtbar im Editorfenster.');
  };

  const buildProduct = () => {
    generateCodeInEditor();
    log('✨ Produkt lebt: Code, Preview und Agent-Workspace wurden erzeugt.');
  };

  const addCard = () => setCards((items) => [...items, { id: makeId(), title: 'Neues Modul', body: blueprint }]);

  const sendChat = () => {
    if (!chatInput.trim()) return;
    log(`🤖 Agent: Ich habe den Auftrag verstanden: ${chatInput}`);
    setChatInput('');
    generateCodeInEditor();
  };

  const downloadPackage = () => {
    const blob = new Blob([generatedPackage], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sovereign-product-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const publishAndValidate = () => {
    setWorkView('pipeline');
    setPipelineState('publishing');
    log('🚀 Publish gestartet: Review-Branch, Dateien und Workflow-Paket werden vorbereitet.');
    window.setTimeout(() => {
      setPipelineState('validating');
      log(`🔎 Validierung läuft mit ${settings.packageManager}/${settings.linter}. Keine Single-Install-Zerstörung bei Monorepo.`);
    }, 450);
    window.setTimeout(() => {
      if (fixLoops < 1) {
        setPipelineState('failed');
        setFixLoops((count) => count + 1);
        log('❌ Workflow-Fehler erkannt: Agent springt zurück in den Editor und patcht sichtbar.');
      } else {
        setPipelineState('green');
        log('✅ Workflows grün. PR kann gemerged werden.');
      }
    }, 900);
  };

  const patchFromPipeline = () => {
    setPipelineState('patching');
    setWorkView('editor');
    const patched = `${currentCode}\n\n// AutoPatch ${fixLoops}: lint/build guard\nexport const validationPatch = {\n  reason: 'CI failure resolved by visible patch loop',\n  linter: '${settings.linter}',\n  packageManager: '${settings.packageManager}',\n  monorepoSafe: ${settings.repoMode === 'monorepo'}\n};\n`;
    setGeneratedCode(patched);
    log('🛠️ Patch sichtbar im Editor erzeugt. Danach erneut Publish & Validate drücken.');
  };

  const mergeWhenGreen = () => {
    if (pipelineState !== 'green') {
      log('⚠️ Merge blockiert: erst grüne Validierung abwarten.');
      return;
    }
    log('🎉 Merge/Patch abgeschlossen. Branch Cleanup vorbereitet.');
  };

  const pipelineBadge = {
    idle: 'Bereit',
    publishing: 'Publishing',
    validating: 'Validating',
    failed: 'Fehler',
    patching: 'Patching',
    green: 'Grün',
  }[pipelineState];

  return (
    <div className="h-screen overflow-hidden bg-stone-50 text-stone-900 font-sans flex flex-col">
      <header className="h-14 bg-white border-b border-stone-200 flex items-center justify-between px-4 shrink-0 shadow-sm z-50">
        <div>
          <h1 className="text-sm font-bold tracking-tight">SOVEREIGN<span className="text-indigo-600">_STUDIO</span></h1>
          <div className="text-[9px] font-bold text-indigo-600 uppercase tracking-widest">Auto-Resolver Product Builder</div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setShowSettings((value) => !value)} className="px-3 py-1.5 bg-indigo-50 border border-indigo-200 text-indigo-700 rounded text-[10px] font-bold hover:bg-indigo-100 flex items-center gap-1"><Settings size={12}/> SETTINGS</button>
          <button onClick={() => log('🧹 Workspace Cleanup vorbereitet.')} className="px-3 py-1.5 bg-rose-50 border border-rose-200 text-rose-700 rounded text-[10px] font-bold hover:bg-rose-100">🧹 CLEANUP</button>
          <button onClick={() => log('🔄 Demo Tree aktualisiert.')} className="px-3 py-1.5 bg-stone-100 border border-stone-200 rounded text-[10px] font-bold hover:bg-stone-200">🔄 REFRESH TREE</button>
        </div>
      </header>

      <div className="h-12 bg-stone-50 border-b border-stone-200 flex items-center justify-between px-4 shrink-0 text-xs overflow-x-auto gap-4">
        <div className="flex items-center gap-2 shrink-0">
          <span className="font-bold text-stone-500 uppercase text-[10px]">GitHub URL:</span>
          <input value={repoUrl} onChange={(event) => setRepoUrl(event.target.value)} className="text-xs px-2 py-1 border border-stone-300 rounded w-64 focus:outline-none focus:border-indigo-500 bg-white" />
          <button onClick={() => log(`📁 Repository verbunden: ${repoUrl}`)} className="px-3 py-1 bg-indigo-600 text-white font-bold rounded hover:bg-indigo-700 text-[10px] uppercase">Repo Laden</button>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <label className="flex items-center gap-2"><span className="font-bold text-stone-500 uppercase text-[10px]">GitHub PAT:</span><input value={accessKey} onChange={(event) => setAccessKey(event.target.value)} type="password" placeholder="nur im Feld" className="text-xs px-2 py-1 border border-stone-300 rounded w-40 focus:outline-none focus:border-indigo-500 bg-white" /></label>
          <label className="flex items-center gap-2">
            <span className="font-bold text-stone-500 uppercase text-[10px]">Gemini Key:</span>
            <input value={geminiKey} onChange={(event) => setGeminiKey(event.target.value)} type="password" placeholder="hier API-Key einfügen" className="text-xs px-2 py-1 border border-stone-300 rounded w-40 focus:outline-none focus:border-indigo-500 bg-white" />
            <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noopener noreferrer" className="text-[10px] px-2 py-1 bg-amber-100 border border-amber-300 text-amber-800 rounded hover:bg-amber-200 font-bold" title="Hier kostenlosen API-Key erstellen">🌐 AI Studio</a>
          </label>
        </div>
      </div>

      {showSettings && <div className="bg-white border-b border-indigo-200 p-3 grid grid-cols-2 lg:grid-cols-6 gap-2 text-[10px] shrink-0">
        <label className="font-bold text-stone-600 uppercase">Repo Typ<select value={settings.repoMode} onChange={(event) => setSettings({ ...settings, repoMode: event.target.value as ProjectSettings['repoMode'] })} className="mt-1 w-full border rounded p-1 bg-stone-50"><option value="single">Single Repo</option><option value="monorepo">Monorepo</option></select></label>
        <label className="font-bold text-stone-600 uppercase">Package Manager<select value={settings.packageManager} onChange={(event) => setSettings({ ...settings, packageManager: event.target.value as ProjectSettings['packageManager'] })} className="mt-1 w-full border rounded p-1 bg-stone-50"><option value="auto">Auto</option><option value="pnpm">pnpm</option><option value="npm">npm</option><option value="yarn">yarn</option><option value="bun">bun</option></select></label>
        <label className="font-bold text-stone-600 uppercase">Install<select value={settings.installStrategy} onChange={(event) => setSettings({ ...settings, installStrategy: event.target.value as ProjectSettings['installStrategy'] })} className="mt-1 w-full border rounded p-1 bg-stone-50"><option value="workspace">Workspace Safe</option><option value="frozen">Frozen Lockfile</option><option value="safe">Safe Default</option></select></label>
        <label className="font-bold text-stone-600 uppercase">Autolinter<select value={settings.linter} onChange={(event) => setSettings({ ...settings, linter: event.target.value as ProjectSettings['linter'] })} className="mt-1 w-full border rounded p-1 bg-stone-50"><option value="auto">Auto</option><option value="eslint">ESLint</option><option value="biome">Biome</option><option value="prettier-eslint">Prettier + ESLint</option></select></label>
        <label className="font-bold text-stone-600 uppercase">Fix Loops<input value={settings.maxFixLoops} onChange={(event) => setSettings({ ...settings, maxFixLoops: Number(event.target.value) || 1 })} type="number" min={1} max={8} className="mt-1 w-full border rounded p-1 bg-stone-50" /></label>
        <label className="font-bold text-stone-600 uppercase">Spezialisierung<input value={settings.specialization} onChange={(event) => setSettings({ ...settings, specialization: event.target.value })} className="mt-1 w-full border rounded p-1 bg-stone-50" /></label>
      </div>}

      <main className="flex-1 flex overflow-hidden relative">
        <section className="flex flex-col w-[320px] shrink-0 border-r border-stone-200 bg-white">
          <div className="p-3 bg-indigo-50 border-b border-indigo-200 shrink-0 shadow-sm">
            <h3 className="text-[11px] font-black text-indigo-800 mb-1 flex justify-between items-center"><span>🔁 PRODUCT AUTO-RESOLVER</span><span className={`px-2 py-0.5 rounded-full text-[9px] uppercase ${pipelineState === 'failed' ? 'bg-red-200 text-red-800' : pipelineState === 'green' ? 'bg-green-200 text-green-800' : 'bg-indigo-200 text-indigo-800'}`}>{pipelineBadge}</span></h3>
            <p className="text-[10px] text-indigo-700 mb-2">Profil: <span className="font-mono font-bold">{settings.repoMode}/{settings.packageManager}/{settings.linter}</span></p>
            <button onClick={buildProduct} className="w-full bg-indigo-600 hover:bg-indigo-700 text-white py-2 rounded text-[11px] font-bold uppercase shadow-sm flex items-center justify-center gap-2"><Rocket size={14}/> Produkt bauen</button>
          </div>

          <div className="p-3 bg-stone-50 border-b border-stone-200 shrink-0">
            <h3 className="text-[11px] font-bold text-stone-700 mb-2">⚡ ARCHITECT BLUEPRINT</h3>
            <textarea value={blueprint} onChange={(event) => setBlueprint(event.target.value)} rows={4} className="w-full p-2 text-[11px] border border-stone-300 rounded focus:outline-none focus:border-indigo-500 resize-none shadow-inner" />
            <div className="flex gap-2 mt-2">
              <button onClick={buildProduct} className="flex-1 bg-stone-800 hover:bg-black text-white py-1.5 rounded text-[11px] font-bold uppercase shadow-sm"><Wand2 size={13} className="inline mr-1"/>Generieren</button>
              <button onClick={addCard} className="shrink-0 bg-yellow-100 hover:bg-yellow-200 border border-yellow-300 text-yellow-800 py-1.5 px-3 rounded text-[11px] font-bold uppercase shadow-sm"><Plus size={13} className="inline mr-1"/>Modul</button>
            </div>
          </div>

          <div className="p-2 bg-indigo-50/50 border-b border-stone-200 flex items-center gap-2 shrink-0">
            <input placeholder="Wo ist die App-Logik? ✨" className="flex-1 text-[11px] p-1.5 border border-stone-300 rounded focus:outline-none focus:border-indigo-500 shadow-inner" />
            <button onClick={() => log('✨ Smart Search Demo ausgeführt.')} className="bg-indigo-100 hover:bg-indigo-200 text-indigo-800 px-3 py-1.5 rounded text-[10px] font-bold uppercase shrink-0">✨ SUCHE</button>
          </div>

          <div className="flex-1 overflow-y-auto bg-white">
            {demoFiles.map((file) => <button key={file.path} onClick={() => { setSelectedFile(file); setWorkView('editor'); log(`📄 Datei gewählt: ${file.path}`); }} className={`w-full p-3 border-b border-stone-100 text-[13px] flex items-center gap-2 text-left hover:bg-stone-50 ${selectedFile.path === file.path ? 'bg-teal-50 text-teal-700 border-l-4 border-l-teal-600 font-semibold' : 'text-stone-600'}`}><span>{file.icon}</span><span className="truncate">{file.path}</span></button>)}
          </div>
        </section>

        <section className="flex-1 min-w-0 flex flex-col bg-stone-50">
          <div className="h-10 bg-stone-50 border-b border-stone-200 flex items-center gap-2 px-2 shrink-0 overflow-x-auto">
            <button onClick={() => setWorkView('editor')} className={`px-2 py-1 text-[9px] font-bold rounded ${workView === 'editor' ? 'bg-stone-900 text-white' : 'bg-stone-100 text-stone-700'}`}><Code2 size={11} className="inline mr-1"/>EDITOR</button>
            <button onClick={() => setWorkView('pipeline')} className={`px-2 py-1 text-[9px] font-bold rounded ${workView === 'pipeline' ? 'bg-stone-900 text-white' : 'bg-stone-100 text-stone-700'}`}><RefreshCw size={11} className="inline mr-1"/>PUBLISH LOOP</button>
            <span className="text-[11px] font-mono text-stone-600 italic truncate mr-2 px-2 max-w-[220px]">{selectedFile.path}</span>
            {['REVIEW','TESTS','DOCS','CI/CD','README','AUTOLINT'].map((label) => <button key={label} onClick={() => log(`✨ ${label} vorbereitet mit ${settings.packageManager}/${settings.linter}.`)} className="px-2 py-1 bg-indigo-100 text-indigo-700 text-[9px] font-bold rounded hover:bg-indigo-200">✨ {label}</button>)}
          </div>

          {workView === 'editor' ? <div className="flex-1 bg-stone-100/30 p-4 overflow-hidden flex flex-col">
            <div className="editor-bg flex-1 rounded-xl shadow-inner relative overflow-hidden flex flex-col bg-stone-950 font-mono border border-stone-800">
              <div className="h-8 bg-stone-900 border-b border-stone-800 flex items-center gap-2 px-3 text-[10px] text-stone-400"><span className="w-2 h-2 rounded-full bg-red-500"/><span className="w-2 h-2 rounded-full bg-yellow-500"/><span className="w-2 h-2 rounded-full bg-green-500"/><span className="ml-2">Monaco-style Code Editor · generated output visible</span></div>
              <div className="flex-1 overflow-auto p-3 text-[12px] text-stone-300 whitespace-pre leading-relaxed">
{currentCode.split('\n').map((line, index) => `${String(index + 1).padStart(3, ' ')} │ ${line}`).join('\n')}
              </div>
            </div>
          </div> : <div className="flex-1 bg-stone-100/30 p-4 overflow-y-auto">
            <div className="bg-white border border-stone-200 rounded-xl shadow-sm p-4">
              <h3 className="text-sm font-black text-stone-900 mb-2">Publish · Validate · Patch Loop</h3>
              <p className="text-xs text-stone-500 mb-4">Ablauf: Code sichtbar erzeugen → Publish/PR vorbereiten → Workflows prüfen → bei Fehler zurück in Editor → Patch ansehen → erneut validieren.</p>
              <div className="grid grid-cols-4 gap-2 mb-4">
                {[['publishing','1 Publish'], ['validating','2 Validate'], ['failed','3 Fehler'], ['green','4 Grün']].map(([state, label]) => <div key={state} className={`p-3 rounded-xl border text-center text-[10px] font-black ${pipelineState === state ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-stone-50 text-stone-500 border-stone-200'}`}>{label}</div>)}
              </div>
              <div className="flex flex-wrap gap-2">
                <button onClick={publishAndValidate} className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-[10px] font-black uppercase">🚀 Publish & Validate</button>
                <button onClick={patchFromPipeline} className="px-4 py-2 bg-amber-100 text-amber-800 border border-amber-200 rounded-lg text-[10px] font-black uppercase">🛠️ Fehler patchen</button>
                <button onClick={mergeWhenGreen} className="px-4 py-2 bg-green-600 text-white rounded-lg text-[10px] font-black uppercase">✅ Merge/Patch</button>
              </div>
              {pipelineState === 'failed' && <div className="mt-4 p-3 bg-red-50 border border-red-200 text-red-800 rounded-xl text-xs"><AlertTriangle size={14} className="inline mr-1"/> Fehler gefunden. Der Agent springt zurück in den Editor und erzeugt einen sichtbaren Patch.</div>}
              {pipelineState === 'green' && <div className="mt-4 p-3 bg-green-50 border border-green-200 text-green-800 rounded-xl text-xs"><CheckCircle size={14} className="inline mr-1"/> Alle Workflows grün. Merge ist freigegeben.</div>}
            </div>
          </div>}

          <div className="h-12 bg-white border-t border-stone-200 flex items-center px-4 gap-3 shrink-0">
            <span className="text-lg">🤖</span>
            <input value={chatInput} onChange={(event) => setChatInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') sendChat(); }} placeholder="Frag den Code-Agenten..." className="flex-1 text-[11px] p-1.5 border border-stone-300 rounded focus:outline-none focus:border-indigo-500 bg-stone-50" />
            <button onClick={sendChat} className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-1.5 rounded text-[10px] font-bold uppercase shadow-sm"><Send size={13}/></button>
          </div>

          <div className="h-16 border-t border-indigo-200 px-4 flex items-center justify-between bg-indigo-50 shrink-0 gap-3">
            <div className="flex-1 min-w-0"><h4 className="text-[10px] font-black text-indigo-800 uppercase">PR-Queue: <span>{cards.length}</span> Module · Fixloop {fixLoops}/{settings.maxFixLoops}</h4><input value={built ? 'feat: generate sovereign product workspace' : ''} readOnly placeholder="Commit Nachricht..." className="w-full text-[10px] p-1 border border-indigo-200 rounded bg-white" /></div>
            <button onClick={publishAndValidate} className="shrink-0 px-6 py-2 bg-indigo-600 text-white rounded-lg font-bold text-[10px] uppercase shadow-sm">🛡️ PUBLISH & VALIDATE</button>
          </div>
        </section>

        <section className="w-[350px] shrink-0 border-l border-stone-200 bg-white flex flex-col">
          <div className="p-3 bg-stone-50 border-b border-stone-200 text-[11px] font-bold text-stone-800 flex items-center justify-between shrink-0"><div><span className="text-indigo-600">✨</span> SYSTEM LOG</div><button onClick={() => setLogs([])} className="text-[9px] text-stone-400 hover:text-stone-600">Leeren</button></div>
          <div className="flex-1 overflow-y-auto p-4 space-y-3 bg-white text-[11px]">
            {built && <div className="p-3 rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-900 shadow-sm"><strong><Eye size={13} className="inline mr-1"/>Living Product aktiv</strong><br/>{cards.map((card) => <button key={card.id} onClick={() => log(`▶ Modul gestartet: ${card.title}`)} className="mt-2 mr-2 px-2 py-1 rounded bg-white border border-emerald-200 text-[10px] font-bold">{card.title}</button>)}</div>}
            <div className="p-3 rounded-xl border border-indigo-200 bg-indigo-50 text-indigo-900 shadow-sm"><strong><Bot size={13} className="inline mr-1"/>No-Code Agent Oberfläche</strong><br/>Explorer, Monaco-style Editor, Chat, Settings, Autolinter und Publish-Loop sind verbunden.</div>
            {logs.map((entry, index) => <div key={`${entry}-${index}`} className="p-3 bg-stone-100 rounded-xl rounded-tl-none border border-stone-200 text-stone-700 shadow-sm break-words">{entry}</div>)}
          </div>
          <div className="border-t border-stone-200 p-3 bg-stone-50">
            <button onClick={downloadPackage} className="w-full bg-stone-900 text-white py-2 rounded-lg text-[10px] font-black uppercase flex items-center justify-center gap-2"><Download size={13}/> Produktpaket sichern</button>
          </div>
        </section>
      </main>
    </div>
  );
}
