"""Single-source evidence-first admin UI served by the backend runtime."""

ENTERPRISE_ADMIN_HTML = r"""<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sovereign Enterprise Admin</title><style>
:root{color-scheme:dark;--bg:#080b10;--panel:#111722;--line:#293246;--text:#f4f7fb;--muted:#9aa8bd;--ok:#55d88b;--warn:#ffc857;--bad:#ff6b6b;--accent:#6ea8fe}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:20px}.top,.actions,.form-grid{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.top h1{font-size:22px;margin-right:auto}input,button,select{min-height:48px;border-radius:9px;border:1px solid var(--line);background:var(--panel);color:var(--text);padding:0 14px}input,select{min-width:220px}button{cursor:pointer;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin-top:16px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px}.card h2{font-size:15px;margin:0 0 10px}.value{font-size:28px;font-weight:800}.muted{color:var(--muted)}.ok{color:var(--ok)}.blocked{color:var(--bad)}.warn{color:var(--warn)}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line);vertical-align:top}code{word-break:break-all}.hidden{display:none}.notice{margin-top:12px;padding:12px;border:1px solid var(--line);border-radius:9px}.actions{margin-top:12px}.section{margin-top:12px}.compact{font-size:12px}.wide{width:100%}@media(max-width:650px){main{padding:12px}.top input,.form-grid input,.form-grid select{width:100%;min-width:0}th:nth-child(4),td:nth-child(4){display:none}}
</style></head><body><main>
<div class="top"><h1>Sovereign Enterprise Admin</h1><input id="key" type="password" placeholder="Admin API Key" autocomplete="off"><button onclick="login()">Anmelden</button><button id="logout" class="hidden" onclick="logout()">Abmelden</button></div>
<div id="message" class="notice muted">Diese Oberfläche zeigt ausschließlich live gelesene Runtime-, Provider-, Knowledge-, pgvector-, Milvus- und Evidence-Daten.</div>
<section id="content" class="hidden">
<div class="actions"><button onclick="refreshAll()">Alles aktualisieren</button><button onclick="runCanary('readiness')">Readiness-Canary</button><button onclick="loadKnowledgeTruth()">Knowledge-Readback</button><button onclick="loadLlmTruth()">LLM-Readback</button></div>
<div id="summary" class="grid"></div>
<div class="card section"><h2>Integrationen</h2><div id="integrations"></div></div>
<div class="card section"><h2>Persistierte Evidence</h2><div id="evidence"></div></div>
<div class="card section"><h2>Import- und Vectorstatus</h2><div id="knowledgeTruth" class="muted">Noch nicht gelesen.</div></div>
<div class="card section"><h2>LLM-Routen und echte Completion-Canaries</h2><div id="llmTruth" class="muted">Noch nicht gelesen.</div></div>
<div class="card section"><h2>LiteLLM-Modellkatalog anbinden</h2>
<div class="form-grid"><select id="providerCatalogModel"></select><select id="providerBillingCategory"></select><select id="providerFundingMode"></select><input id="providerMarkupMultiplier" type="number" min="0" step="1" value="8" placeholder="Markup"><input id="providerPriority" type="number" step="1" value="50" placeholder="Priorität"></div>
<div class="actions"><button onclick="loadProviderCatalog()">Katalog laden</button><button onclick="attachCatalogModel()">Modell mit Canary anbinden</button><button onclick="loadProviderDeployments()">Deployments laden</button></div><div id="providerResult" class="notice muted">Manuelle Preisbearbeitung ist deaktiviert; LiteLLM-Modellinfo ist Preisautorität.</div><div id="providerDeployments"></div></div>
</section>
<script>
let token='';const q=id=>document.getElementById(id);function headers(){return{'Authorization':'Bearer '+token,'Content-Type':'application/json'}}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...headers(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||d.message||('HTTP '+r.status));e.payload=d;e.status=r.status;throw e}return d}async function boundedFetch(path,opt={}){return api(path,opt)}
async function login(){token=q('key').value.trim();if(!token)return;try{const data=await api('/api/admin/ping');if(data.ok!==true||!data.id)throw new Error('Admin-Identität nicht bestätigt');q('content').classList.remove('hidden');q('logout').classList.remove('hidden');q('key').value='';await refreshAll()}catch(e){token='';q('message').textContent='Anmeldung fehlgeschlagen: '+e.message;q('message').className='notice blocked'}}function logout(){token='';q('content').classList.add('hidden');q('logout').classList.add('hidden');q('message').textContent='Abgemeldet.';q('message').className='notice muted'}
function metric(label,value,cls=''){return`<div class="card"><h2>${esc(label)}</h2><div class="value ${cls}">${esc(value)}</div></div>`}function blockerLabel(code){return({provider_quota_exhausted:'Provider-Kontingent erschöpft',provider_secret_missing:'Zugang ausstehend – kein Secret im sicheren Übergabepfad',provider_key_fingerprint_missing:'Provider-Key muss für den Quota-Scope erneut bestätigt werden',provider_recovery_policy_invalid:'Free-Quota-Policy konnte nicht sicher bestätigt werden',llm_route_attempts:'Routenversuche blockiert',llm_route_revolver_state:'Revolver-Status blockiert',manual_llm_price_editing_disabled:'Manuelle Preisbearbeitung deaktiviert',free_route_user_charge_nonzero:'Free-Route würde Nutzer belasten'})[code]||code||''}
async function refreshAll(){try{q('message').textContent='Live-Daten werden gelesen…';q('message').className='notice muted';const[o,e]=await Promise.all([api('/api/admin/platform/v1/overview'),api('/api/admin/platform/v1/evidence?limit=30')]);render(o,e);await Promise.all([loadKnowledgeTruth(),loadLlmTruth(),loadProviderCatalog(),loadProviderDeployments()]);q('message').textContent='Live-Readback bestätigt. Keine UI-erzeugte Wahrheit.';q('message').className='notice ok'}catch(err){q('message').textContent='Readback fehlgeschlagen: '+err.message;q('message').className='notice blocked'}}
function render(o,e){const s=o.statistics||{};const vector=s.vectors||s.vectorMemory||{};const milvus=vector.milvus||s.milvus||{};const pg=vector.pgvector||s.pgvector||{};q('summary').innerHTML=[metric('Runtime',o.status||'unknown',o.status==='verified'?'ok':'blocked'),metric('Revision',o.runtime?.revision||o.runtime?.sourceRevision||'unverified'),metric('pgvector',pg.total??pg.count??s.knowledgeVectors??'—'),metric('Milvus indexed',milvus.indexed??'—'),metric('Milvus pending',milvus.pending??'—',Number(milvus.pending)>0?'warn':''),metric('Milvus blocked',milvus.blocked??'—',Number(milvus.blocked)>0?'blocked':'')].join('');const ints=o.integrations||[];q('integrations').innerHTML=ints.length?`<table><thead><tr><th>Name</th><th>Status</th><th>Evidence</th></tr></thead><tbody>${ints.map(i=>`<tr><td>${esc(i.name||i.id)}</td><td class="${i.status==='verified'?'ok':'blocked'}">${esc(i.status)}</td><td><code>${esc(i.evidenceSha256||i.blocker||i.detail||'')}</code></td></tr>`).join('')}</tbody></table>`:'Keine Integrationsdaten.';const rows=e.evidence||[];q('evidence').innerHTML=rows.length?`<table><thead><tr><th>Zeit</th><th>Scope</th><th>SHA-256</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.observedAt||r.createdAt||'')}</td><td>${esc(r.scope||r.status||'')}</td><td><code>${esc(r.evidenceSha256||'')}</code></td></tr>`).join('')}</tbody></table>`:'Keine Evidence-Einträge.'}
async function loadKnowledgeTruth(){const host=q('knowledgeTruth');try{const data=await boundedFetch('/api/admin/knowledge/sources');const runtime=data.runtime||{};const usable=runtime.importsUsable===true;host.innerHTML=`<div class="grid">${metric('Bereite Quellen',runtime.ready_sources??0,usable?'ok':'warn')}${metric('Blockierte Quellen',runtime.blocked_sources??0,Number(runtime.blocked_sources)>0?'blocked':'')}${metric('Vektoren',(runtime.embedded_blocks??0)+'/'+(runtime.unique_blocks??0))}${metric('Fehlende Embeddings',runtime.missing_embeddings??0,Number(runtime.missing_embeddings)>0?'warn':'ok')}${metric('Verwaiste Links',runtime.orphan_links??0,Number(runtime.orphan_links)>0?'blocked':'ok')}</div><div class="notice ${Number(data.reconciledStaleImports||0)>0?'warn':'muted'}">${Number(data.reconciledStaleImports||0)>0?Number(data.reconciledStaleImports)+' unterbrochener Import wurde fail-closed als blockiert markiert.':'Keine unterbrochenen Imports erkannt.'} Speicher: ${esc(runtime.storage||'unverified')}</div>`}catch(e){host.innerHTML='<span class="blocked">Knowledge-Readback fehlgeschlagen: '+esc(e.message)+'</span>'}}
async function loadLlmTruth(){const host=q('llmTruth');try{const data=await boundedFetch('/api/admin/llm/routes');const routes=data.routes||[];const profiles=data.executionProfiles||[];const profileCards=profiles.map(p=>metric(p.profileId,(p.maxForegroundAgents||1)+' aktiv + '+(p.maxBackgroundAgents||0)+' Background',p.enabled?'ok':'warn')).join('');if(!routes.length){host.innerHTML=(profileCards?'<div class="grid">'+profileCards+'</div>':'')+'<div class="notice warn">Keine aktive Route im Resolver-Magazin.</div>';return}host.innerHTML=(profileCards?'<div class="grid">'+profileCards+'</div>':'')+`<div class="notice muted">Resolver: ${esc(data.resolverPolicy?.routingOwner||'unverified')} · Paid-Fallback: ${esc(data.resolverPolicy?.paidQuotaFallback||'unverified')}</div><table><thead><tr><th>Route</th><th>Provider</th><th>Billing</th><th>Agentenprofil</th><th>Canary</th></tr></thead><tbody>${routes.map(r=>`<tr><td>${esc(r.modelName||r.modelId||r.id)}</td><td>${esc(r.provider||'')}</td><td>${esc(r.billingCategory||r.tier||'')} ×${esc(r.markupMultiplier??'—')}</td><td>${esc(r.executionProfile||'unverified')}<div class="compact muted">1 aktiv + ${esc(r.maxBackgroundAgents??0)} Background · Workspace ${r.repositoryExecutionAllowed?'ja':'nein'}</div></td><td><button onclick="healthcheckRoute('${esc(r.id)}')">Prüfen</button><div id="health_${esc(r.id)}" class="compact muted">${esc(blockerLabel(r.lastErrorCode||r.blocker))}</div></td></tr>`).join('')}</tbody></table>`}catch(e){host.innerHTML='<span class="blocked">LLM-Readback fehlgeschlagen: '+esc(e.message)+'</span>'}}
async function healthcheckRoute(id){const el=q('health_'+id);el.textContent='Canary läuft…';try{const d=await boundedFetch('/api/admin/llm/routes/'+id+'/healthcheck',{method:'POST'});const blocker=d.blocker||d.errorCode||'';el.textContent=d.ok?'Completion bestätigt':blockerLabel(blocker)||d.health||'blockiert';el.className='compact '+(d.ok?'ok':'blocked')}catch(e){const blocker=e.payload?.blocker||e.payload?.errorCode||'';el.textContent=blockerLabel(blocker)||e.message;el.className='compact blocked'}}
function fillSelect(id,rows){q(id).innerHTML=(rows||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.label||x.id)}</option>`).join('')}async function loadProviderCatalog(){try{const[presets,catalog]=await Promise.all([api('/api/admin/llm/provider-presets'),api('/api/admin/llm/model-catalog')]);fillSelect('providerBillingCategory',presets.billingCategories);fillSelect('providerFundingMode',presets.fundingModes);q('providerCatalogModel').innerHTML=(catalog.models||[]).map(m=>`<option value="${esc(m.modelId)}">${esc(m.modelId)} · ${m.pricingVerified?'Preis bestätigt':'Preis offen'}</option>`).join('');q('providerResult').textContent='LiteLLM-Katalog gelesen: '+(catalog.models||[]).length+' Modelle. manual_llm_price_editing_disabled';q('providerResult').className='notice ok'}catch(e){q('providerResult').textContent='Katalog blockiert: '+e.message;q('providerResult').className='notice blocked'}}
async function attachCatalogModel(){const body={modelId:q('providerCatalogModel').value,displayName:q('providerCatalogModel').value,billingCategory:document.getElementById('providerBillingCategory').value,fundingMode:document.getElementById('providerFundingMode').value,markupMultiplier:Number(document.getElementById('providerMarkupMultiplier').value||0),priority:Number(q('providerPriority').value||50)};try{const d=await api('/api/admin/llm/model-catalog/attach',{method:'POST',body:JSON.stringify(body)});q('providerResult').textContent='Route '+d.routeId+' gespeichert; Canary '+(d.canaryRequestId||'ohne Upstream-ID')+'.';q('providerResult').className='notice ok';await loadLlmTruth()}catch(e){q('providerResult').textContent=blockerLabel(e.payload?.blocker)||e.message;q('providerResult').className='notice blocked'}}
function providerCredentialLabel(d){return({stored_in_litellm:'In LiteLLM gespeichert',registered:'Registriert',consumed:'Owner-Eingabe verbraucht',awaiting_owner_input:'Owner-Eingabe erforderlich',missing:'Zugang fehlt – erneut sicher eintragen'})[d.credentialState]||d.credentialState||'unverified'}async function loadProviderDeployments(){const host=q('providerDeployments');try{const d=await api('/api/admin/llm/provider-deployments');const rows=d.deployments||[];host.innerHTML=rows.length?`<table><thead><tr><th>Deployment</th><th>Status</th><th>Kosten</th><th>Aktion</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.providerName||x.routeId)}<div class="compact muted">${esc(providerCredentialLabel(x))} · ${esc(x.keyHint||'kein Key-Hinweis')}</div></td><td class="${x.status==='ready'?'ok':'warn'}">${esc(x.status)}<div class="compact blocked">${esc(blockerLabel(x.lastErrorCode)||'')}</div></td><td>${esc(x.billingCategory||'')} ×${esc(x.markupMultiplier??'—')}<div class="compact muted">${esc(x.fundingMode||'provider_priced')} · In ${esc(x.inputUsdPerMillion??'—')} / Out ${esc(x.outputUsdPerMillion??'—')}</div></td><td><button onclick="refreshProviderOwnerInput('${esc(x.routeId)}')">Owner-Eingabe</button> <button onclick="prepareProviderFreeQuota('${esc(x.routeId)}')">Free-Quota vorbereiten</button> <button onclick="activateProvider('${esc(x.routeId)}')">Aktivieren</button></td></tr>`).join('')}</tbody></table>`:'<div class="muted">Keine Provider-Deployments.</div>'}catch(e){host.innerHTML='<span class="blocked">Deployment-Readback fehlgeschlagen: '+esc(e.message)+'</span>'}}
async function refreshProviderOwnerInput(routeId){try{const d=await api('/api/admin/llm/provider-deployments/'+routeId+'/owner-input',{method:'POST'});window.open(d.ownerUrl,'_blank','noopener');await loadProviderDeployments()}catch(e){q('providerResult').textContent=e.message;q('providerResult').className='notice blocked'}}async function prepareProviderFreeQuota(routeId){try{const d=await api('/api/admin/llm/provider-deployments/'+routeId+'/owner-input',{method:'POST',body:JSON.stringify({billingCategory:'free',fundingMode:'provider_free_quota',markupMultiplier:0})});q('providerResult').textContent='Free-Quota vorbereitet. Provider-Key jetzt erneut sicher eintragen; Aktivierung erfolgt erst nach echter Canary.';q('providerResult').className='notice warn';window.open(d.ownerUrl,'_blank','noopener');await loadProviderDeployments()}catch(e){q('providerResult').textContent=blockerLabel(e.payload?.blocker)||e.message;q('providerResult').className='notice blocked'}}async function activateProvider(routeId){try{const d=await api('/api/admin/llm/provider-deployments/'+routeId+'/activate',{method:'POST'});q('providerResult').textContent='Providerstatus: '+d.status;q('providerResult').className='notice '+(d.ok?'ok':'blocked');await Promise.all([loadProviderDeployments(),loadLlmTruth()])}catch(e){q('providerResult').textContent=blockerLabel(e.payload?.blocker)||e.message;q('providerResult').className='notice blocked'}}
async function runCanary(scope){try{const d=await api('/api/admin/platform/v1/canaries',{method:'POST',body:JSON.stringify({scope,confirmed:true})});q('message').textContent='Canary '+scope+': '+(d.status||'abgeschlossen');q('message').className='notice '+(d.ok?'ok':'blocked');await refreshAll()}catch(e){q('message').textContent='Canary fehlgeschlagen: '+e.message;q('message').className='notice blocked'}}
</script></main></body></html>"""
