"""Static Android-friendly FreeLLM provider credential page."""

FREELLM_PROVIDER_KEYS_PAGE = r"""<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FreeLLM Provider-Zugänge</title>
<style>
:root{color-scheme:dark;--bg:#0d1117;--card:#161b22;--line:#30363d;--text:#e6edf3;--muted:#8b949e;--ok:#238636;--accent:#1f6feb;--warn:#d29922}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,sans-serif;padding:max(1rem,env(safe-area-inset-top)) max(1rem,env(safe-area-inset-right)) max(1rem,env(safe-area-inset-bottom)) max(1rem,env(safe-area-inset-left))}.wrap{max-width:52rem;margin:auto}.card{background:var(--card);border:1px solid var(--line);border-radius:1rem;padding:1rem;margin:1rem 0}input,button{font:inherit;min-height:3rem;border-radius:.7rem}input{width:100%;background:var(--bg);color:var(--text);border:1px solid var(--line);padding:.75rem}button{border:0;padding:.7rem 1rem;font-weight:700;cursor:pointer;background:var(--accent);color:white}.keyless{background:var(--warn);color:#111}.off{background:#30363d}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));gap:.8rem}.muted{color:var(--muted);font-size:.9rem}.ok{color:#7ee787}.error{color:#ff7b72}.row{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center}.badge{font-size:.8rem;border:1px solid var(--line);border-radius:999px;padding:.2rem .55rem}h1{font-size:clamp(1.35rem,5vw,2rem)}h2{font-size:1.05rem;margin:.2rem 0 .5rem}@media(hover:hover){button:hover{filter:brightness(1.12)}}
</style></head><body><main class="wrap"><h1>FreeLLM Provider-Zugänge</h1><p class="muted">Keys werden ausschließlich über die geschützte Owner-Eingabe als 0600-Datei gespeichert. Rohwerte erscheinen weder hier noch in PostgreSQL.</p>
<section id="login" class="card"><label for="admin">Admin-Zugang</label><input id="admin" type="password" autocomplete="off"><div class="row" style="margin-top:.8rem"><button id="loginButton">Provider laden</button></div><p id="loginMessage" class="error"></p></section>
<section id="content" hidden><div class="row"><button class="off" id="reload">Neu laden</button><a href="/owner-approvals" style="color:#58a6ff">Offene Owner-Eingaben</a></div><p id="message"></p><div id="providers" class="grid"></div></section></main>
<script>
let admin='';const q=id=>document.getElementById(id);function headers(){return {'Authorization':'Bearer '+admin};}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function api(path,options={}){const response=await fetch(path,{cache:'no-store',credentials:'same-origin',mode:'same-origin',redirect:'error',...options,headers:{...headers(),...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||data.blocker||'Anfrage fehlgeschlagen');return data;}
function render(rows){q('providers').innerHTML=rows.map(p=>`<article class="card"><div class="row"><h2>${esc(p.label)}</h2><span class="badge">${p.keyless?'keyless':'API-Key'}</span></div><p class="muted">${p.configured?'Konfiguriert':'Noch nicht konfiguriert'}${p.fingerprintSha256?' · Fingerprint '+esc(p.fingerprintSha256.slice(0,12))+'…':''}</p>${p.privacyNotice?`<p class="muted">${esc(p.privacyNotice)}</p>`:''}${p.keyless&&p.configured?'<span class="badge ok">Aktiviert</span>':`<button data-provider="${esc(p.providerId)}" data-keyless="${p.keyless}" class="${p.keyless?'keyless':''}">${p.keyless?'Keyless aktivieren':'Key sicher eintragen'}</button>`}</article>`).join('');document.querySelectorAll('[data-provider]').forEach(button=>button.onclick=()=>act(button));}
async function load(){const data=await api('/api/admin/llm/freellm/provider-credentials');render(data.providers||[]);q('login').hidden=true;q('content').hidden=false;}
async function act(button){const id=button.dataset.provider;const keyless=button.dataset.keyless==='true';q('message').className='muted';q('message').textContent='Verarbeite…';try{if(keyless){const data=await api('/api/admin/llm/freellm/provider-credentials/'+encodeURIComponent(id)+'/keyless',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:true})});q('message').className='ok';q('message').textContent=data.enabled?'Keyless-Provider aktiviert; FreeLLM übernimmt ihn innerhalb von 15 Sekunden.':'Aktivierung nicht bestätigt.';await load();}else{const data=await api('/api/admin/llm/freellm/provider-credentials/'+encodeURIComponent(id)+'/owner-input',{method:'POST'});location.assign(data.ownerUrl);}}catch(error){q('message').className='error';q('message').textContent=error.message;}}
q('loginButton').onclick=async()=>{admin=q('admin').value.trim();q('admin').value='';try{await load();}catch(error){admin='';q('loginMessage').textContent=error.message;}};q('reload').onclick=load;
</script></body></html>"""
